export type Language = 'en' | 'fa-AF' | 'ps-AF'
export type TranslationKey = keyof typeof translations.en

const translations = {
  en: {
    dashboard: 'Dashboard', trade: 'Trade', transactions: 'Transactions', cashAccounts: 'Cash & Accounts', people: 'People', debts: 'Debts', rates: 'Rates', reports: 'Reports',
    workspace: 'Workspace', goodMorning: 'Good morning, Mohammad.', businessStand: 'Here is where your business stands today.', newTrade: 'New trade', localWorkspace: 'Local workspace', supabaseLoaded: 'Supabase credentials loaded',
    totalPosition: 'Total position', todayVolume: "Today's volume", realizedProfit: 'Realized profit', whereMoney: 'Where your money is', liveBalances: 'Live balances across all accounts', needsAttention: 'Needs attention', reviewItems: 'Items requiring your review', recentActivity: 'Recent activity', traceable: 'Every movement, recorded and traceable',
    buy: 'Buy currency', sell: 'Sell currency', exchange: 'Exchange currency', receive: 'Receive money', pay: 'Pay money', debtCredit: 'Debt / Credit', transfer: 'Transfer cash', expense: 'Expense', ownerCapital: 'Owner capital', bankMovement: 'Bank movement', hawala: 'Hawala', optionalModule: 'Optional module',
    stillOffline: 'Offline', online: 'Online', pendingSync: 'Pending sync', syncConflict: 'Sync conflict', lastSync: 'Last sync', postTrade: 'Post trade', recordTrade: 'Record a trade', customer: 'Customer or counterparty', sellAmount: 'Sell', buyAmount: 'Buy', exchangeRate: 'Exchange rate', marketRate: 'Market rate',
    viewAll: 'View all', history: 'History', posted: 'Posted', pending: 'Pending', mainBranch: 'Main branch', cash: 'Cash', bank: 'Bank', today: 'Today', completed: 'Completed', administration: 'Administration', reconciliation: 'Reconciliation', teamDevices: 'Team & Devices', settings: 'Settings', readOnlyInspection: 'Read-only inspection', publicPreview: 'Public preview', activeBranch: 'Active branch', moreActions: 'More actions', connected: 'Connected', offlineMode: 'Offline mode', justNow: 'just now', retailRateContext: 'Retail · Kabul Central · AFN per USD', awaitingLiveLedger: 'Awaiting live ledger data', ledgerDerivedAfn: 'Ledger-derived AFN equivalent', liveBusiness: 'Live business', authoritativeSnapshot: 'Authoritative Supabase snapshot', moneyLocations: 'Money locations', postedToday: 'Posted today', refreshLiveView: 'Refresh live view', journalBalances: 'Live balances from journal lines', assetLocation: 'Authoritative asset location', liveReviewQueue: 'Live review queue', loadingReviewQueue: 'Loading live review queue.', exportCsv: 'Export CSV', transaction: 'Transaction', direction: 'Direction', time: 'Time', newTransaction: 'New transaction', close: 'Close', amount: 'Amount', currency: 'Currency', note: 'Note', location: 'Location', postOperation: 'Post operation', expenseCategory: 'Expense category', fromLocation: 'From location', toLocation: 'To location', varianceReason: 'Variance reason', submitCashCount: 'Submit cash count', beneficiary: 'Beneficiary', destination: 'Destination', referenceCode: 'Reference code', postHawalaSend: 'Post Hawala send', reportCenter: 'Report center', exportPdf: 'Export PDF', printReport: 'Print report', rateBoard: 'Rate board', buyRate: 'Buy rate', sellRate: 'Sell rate', debtCreditTitle: 'Debt & credit', countedAfn: 'Counted AFN', countedUsd: 'Counted USD', helpSupport: 'Help & support', closeHelp: 'Close help', closeTrade: 'Close trade', closeOperation: 'Close operation', closeSettlement: 'Close settlement',
  },
  'fa-AF': {
    dashboard: 'داشبورد', trade: 'معامله', transactions: 'معاملات', cashAccounts: 'صندوق و حساب‌ها', people: 'اشخاص', debts: 'قرض و بدهی', rates: 'نرخ‌ها', reports: 'گزارش‌ها',
    workspace: 'محیط کاری', goodMorning: 'صبح بخیر، محمد.', businessStand: 'وضعیت امروز تجارت شما در اینجا است.', newTrade: 'معامله جدید', localWorkspace: 'محیط کاری محلی', supabaseLoaded: 'تنظیمات اتصال بارگذاری شد',
    totalPosition: 'مجموع دارایی', todayVolume: 'حجم امروز', realizedProfit: 'مفاد تحقق‌یافته', whereMoney: 'پول من کجا است؟', liveBalances: 'موجودی زنده همه حساب‌ها', needsAttention: 'نیازمند توجه', reviewItems: 'مواردی که نیاز به بررسی دارند', recentActivity: 'فعالیت اخیر', traceable: 'هر حرکت ثبت و قابل پیگیری است',
    buy: 'خرید ارز', sell: 'فروش ارز', exchange: 'تبدیل ارز', receive: 'دریافت پول', pay: 'پرداخت پول', debtCredit: 'قرض / اعتبار', transfer: 'انتقال پول', expense: 'مصرف', ownerCapital: 'سرمایه مالک', bankMovement: 'حرکت بانکی', hawala: 'حواله', optionalModule: 'بخش اختیاری',
    stillOffline: 'آفلاین', online: 'آنلاین', pendingSync: 'در انتظار همگام‌سازی', syncConflict: 'تعارض همگام‌سازی', lastSync: 'آخرین همگام‌سازی', postTrade: 'ثبت معامله', recordTrade: 'ثبت معامله', customer: 'مشتری یا طرف معامله', sellAmount: 'فروش', buyAmount: 'خرید', exchangeRate: 'نرخ تبدیل', marketRate: 'نرخ بازار',
    viewAll: 'مشاهده همه', history: 'تاریخچه', posted: 'ثبت‌شده', pending: 'در انتظار', mainBranch: 'شعبه اصلی', cash: 'نقدی', bank: 'بانک', today: 'امروز', completed: 'تکمیل‌شده', administration: 'مدیریت', reconciliation: 'تطبیق حساب', teamDevices: 'تیم و دستگاه‌ها', settings: 'تنظیمات', readOnlyInspection: 'بررسی فقط‌خواندنی', publicPreview: 'پیش‌نمایش عمومی', activeBranch: 'شعبه فعال', moreActions: 'اقدامات بیشتر', connected: 'متصل', offlineMode: 'حالت آفلاین', justNow: 'همین اکنون', retailRateContext: 'پرچون · کابل مرکزی · افغانی در برابر دالر', awaitingLiveLedger: 'در انتظار اطلاعات زنده دفتر کل', ledgerDerivedAfn: 'معادل افغانی بر اساس دفتر کل', liveBusiness: 'تجارت زنده', authoritativeSnapshot: 'تصویر معتبر Supabase', moneyLocations: 'محل‌های پول', postedToday: 'ثبت‌شده امروز', refreshLiveView: 'تازه‌سازی نمای زنده', journalBalances: 'موجودی زنده از خطوط دفتر کل', assetLocation: 'محل معتبر دارایی', liveReviewQueue: 'صف بررسی زنده', loadingReviewQueue: 'صف بررسی زنده در حال بارگذاری است.', exportCsv: 'صدور CSV', transaction: 'معامله', direction: 'جهت', time: 'زمان', newTransaction: 'معامله جدید', close: 'بستن', amount: 'مقدار', currency: 'ارز', note: 'یادداشت', location: 'محل', postOperation: 'ثبت عملیات', expenseCategory: 'دسته‌بندی مصرف', fromLocation: 'محل مبدأ', toLocation: 'محل مقصد', varianceReason: 'دلیل تفاوت', submitCashCount: 'ثبت شمارش نقدی', beneficiary: 'ذی‌نفع', destination: 'مقصد', referenceCode: 'کد مرجع', postHawalaSend: 'ثبت ارسال حواله', reportCenter: 'مرکز گزارش', exportPdf: 'صدور PDF', printReport: 'چاپ گزارش', rateBoard: 'تابلوی نرخ', buyRate: 'نرخ خرید', sellRate: 'نرخ فروش', debtCreditTitle: 'قرض و اعتبار', countedAfn: 'شمارش افغانی', countedUsd: 'شمارش دالر', helpSupport: 'کمک و پشتیبانی', closeHelp: 'بستن کمک', closeTrade: 'بستن معامله', closeOperation: 'بستن عملیات', closeSettlement: 'بستن تسویه',
  },
  'ps-AF': {
    dashboard: 'ډشبورډ', trade: 'راکړه ورکړه', transactions: 'معاملې', cashAccounts: 'صندوق او حسابونه', people: 'خلک', debts: 'پور', rates: 'نرخونه', reports: 'راپورونه',
    workspace: 'کاري ځای', goodMorning: 'سهار مو پخیر، محمد.', businessStand: 'ستاسو د سوداګرۍ د نن ورځې حالت دلته دی.', newTrade: 'نوې راکړه ورکړه', localWorkspace: 'ځايي کاري ځای', supabaseLoaded: 'د اتصال معلومات چمتو دي',
    totalPosition: 'ټوله شتمني', todayVolume: 'د نن ورځې حجم', realizedProfit: 'ترلاسه شوې ګټه', whereMoney: 'زما پیسې چېرته دي؟', liveBalances: 'د ټولو حسابونو اوسنی بیلانس', needsAttention: 'پاملرنې ته اړتیا', reviewItems: 'هغه موارد چې ستاسو کتنې ته اړتیا لري', recentActivity: 'وروستی فعالیت', traceable: 'هر حرکت ثبت او د تعقیب وړ دی',
    buy: 'د اسعارو پېرود', sell: 'د اسعارو پلور', exchange: 'د اسعارو تبادله', receive: 'پیسې ترلاسه کول', pay: 'پیسې ورکول', debtCredit: 'پور / اعتبار', transfer: 'د صندوق انتقال', expense: 'لګښت', ownerCapital: 'د مالک پانګه', bankMovement: 'بانکي حرکت', hawala: 'حواله', optionalModule: 'اختیاري برخه',
    stillOffline: 'آفلاین', online: 'آنلاین', pendingSync: 'همغږۍ ته په تمه', syncConflict: 'د همغږۍ شخړه', lastSync: 'وروستۍ همغږي', postTrade: 'راکړه ورکړه ثبتول', recordTrade: 'راکړه ورکړه ثبتول', customer: 'پېرودونکی یا مقابل لوری', sellAmount: 'پلور', buyAmount: 'پېرود', exchangeRate: 'د تبادلې نرخ', marketRate: 'د بازار نرخ',
    viewAll: 'ټول کتل', history: 'تاریخچه', posted: 'ثبت شوی', pending: 'په تمه', mainBranch: 'اصلي څانګه', cash: 'نغدې', bank: 'بانک', today: 'نن', completed: 'بشپړ شوی', administration: 'اداره', reconciliation: 'تصفیه حساب', teamDevices: 'ټیم او وسایل', settings: 'امستنې', readOnlyInspection: 'یوازې د لوستلو کتنه', publicPreview: 'عامه مخکتنه', activeBranch: 'فعاله څانګه', moreActions: 'نورې کړنې', connected: 'نښلول شوی', offlineMode: 'آفلاین حالت', justNow: 'همدا اوس', retailRateContext: 'پرچون · مرکزي کابل · د یو ډالر په بدل کې افغانۍ', awaitingLiveLedger: 'د ژوندي دفتر معلوماتو ته په تمه', ledgerDerivedAfn: 'د دفتر پر بنسټ د افغانیو معادل', liveBusiness: 'ژوندۍ سوداګري', authoritativeSnapshot: 'د Supabase باوري انځور', moneyLocations: 'د پیسو ځایونه', postedToday: 'نن ثبت شوي', refreshLiveView: 'ژوندۍ کتنه تازه کول', journalBalances: 'د دفتر له کرښو څخه اوسني بیلانسونه', assetLocation: 'د شتمنۍ باوري ځای', liveReviewQueue: 'د ژوندۍ کتنې کتار', loadingReviewQueue: 'د ژوندۍ کتنې کتار لوډېږي.', exportCsv: 'CSV صادرول', transaction: 'معامله', direction: 'لوری', time: 'وخت', newTransaction: 'نوې معامله', close: 'تړل', amount: 'مقدار', currency: 'اسعار', note: 'یادښت', location: 'ځای', postOperation: 'عملیات ثبتول', expenseCategory: 'د لګښت کټګوري', fromLocation: 'د پیل ځای', toLocation: 'د پای ځای', varianceReason: 'د توپیر دلیل', submitCashCount: 'د نغدو شمېر ثبتول', beneficiary: 'ګټه اخیستونکی', destination: 'مقصد', referenceCode: 'د مرجع کوډ', postHawalaSend: 'حواله لېږل ثبتول', reportCenter: 'د راپور مرکز', exportPdf: 'PDF صادرول', printReport: 'راپور چاپول', rateBoard: 'د نرخونو تخته', buyRate: 'د پېرود نرخ', sellRate: 'د پلور نرخ', debtCreditTitle: 'پور او اعتبار', countedAfn: 'شمېرل شوې افغانۍ', countedUsd: 'شمېرل شوي ډالر', helpSupport: 'مرسته او ملاتړ', closeHelp: 'مرسته تړل', closeTrade: 'معامله تړل', closeOperation: 'عملیات تړل', closeSettlement: 'تسویه تړل',
  },
} as const

export function translate(language: Language, key: TranslationKey): string { return translations[language][key] ?? translations.en[key] }
export function isRtl(language: Language): boolean { return language !== 'en' }
export function requiredTranslationKeys(): TranslationKey[] { return Object.keys(translations.en) as TranslationKey[] }
export function hasCompleteTranslations(language: Language): boolean { return requiredTranslationKeys().every((key) => Boolean(translations[language][key])) }
