import type { Language } from "./i18n";

const copy = {
  en: {
    sarafiTagline: "Digital daftar for Sarafi shops",
    owner: "Owner",
    cashier: "Cashier",
    manager: "Manager",
    accountant: "Accountant",
    viewer: "Viewer",
    complianceOfficer: "Compliance officer",
    businessGroup: "Business",
    teamGroup: "Team",
    settingsGroup: "Settings",
    advancedGroup: "Advanced",
    importData: "Import data",
    connectionNotice: "Your shop data is connected",
    yourBusiness: "Your business",
    assignedBranch: "Assigned branch",
    activeBranchSelected: "This is your active branch.",
    signOut: "Sign out",
    showAmounts: "Show amounts",
    hideAmounts: "Hide amounts",
    changeLanguage: "Change language",
    openHelp: "Open help",
    coreCashierActions: "Daily cashier actions",
    liveBuyRate: "Current buy rate",
    liveSellRate: "Current sell rate",
    liveRate: "Current rate",
    rateCalculator: "Rate calculator amount",
    businessDate: "Business date",
    allTime: "All time",
    status: "Status",
    shopAction: "SHOP ACTION",
    income: "Income",
    ownerWithdrawal: "Owner withdrawal",
    bankDeposit: "Bank deposit",
    bankWithdrawal: "Bank withdrawal",
    rent: "Rent",
    salary: "Salary",
    utilities: "Utilities",
    internet: "Internet",
    transport: "Transport",
    other: "Other",
    reasonReference: "Reason or reference",
    shopCheck:
      "SARAFI checks your access, shop, and money details before saving this action.",
    helpIntro:
      "Use the main menu to move between daily shop tasks. Financial actions are saved only after you sign in and SARAFI verifies them.",
    openingBalance: "Opening money",
    recordOpeningMoney: "Record opening money",
    startingAmount: "Amount in this currency",
    afnValue: "Value in AFN",
    saveOpeningMoney: "Save opening money",
    openingMoneyNote:
      "Use this only for money the shop already had before starting SARAFI. It is not profit.",
    backHome: "Back to Home",
    workspaceSection: "This section is available from the main menu.",
    transactionsDescription:
      "Review recorded shop activity and past transactions.",
    moneyDescription:
      "See how much money you have in each currency and where it is kept.",
    peopleDescription: "Find customers and Sarafs, and see who owes whom.",
    debtsDescription:
      "Record and review money people owe you and money you owe them.",
    ratesDescription: "See the shop’s approved buy and sell rates.",
    reportsDescription: "Prepare business, profit, and transaction reports.",
    teamDescription: "Manage employees, devices, and approvals.",
    settingsDescription:
      "Manage your shop, languages, currencies, and security.",
    teamAccess: "Team access",
    teamIntro:
      "See who can use the shop, which devices are active, and what needs approval.",
    active: "Active",
    suspended: "Suspended",
    accessOn: "Access on",
    accessOff: "Access off",
    extraSecurityRequired: "Extra sign-in security required",
    normalSecurity: "Normal sign-in security",
    registeredDevices: "Registered devices",
    lastSeen: "Last seen",
    revoked: "Revoked",
    approvalInbox: "Approval requests",
    approvalRequest: "Approval request",
    requested: "Requested",
    review: "Review",
    noTeam: "No employees have been added yet.",
    noDevices: "No devices have been registered yet.",
    noApprovals: "There are no approval requests.",
    selfApprovalRule: "One person cannot approve their own request.",
    accessRuleNote:
      "Access, branch, cashbox, device, and approval rules are checked automatically when an action is saved.",
    whereIsMoney: "Where is my money?",
    moneyIntro:
      "Money by currency and place, with every amount linked to a recorded transaction.",
    allCurrencies: "All currencies",
    currencyFirst: "By currency",
    locationFirst: "By location",
    printSnapshot: "Print this view",
    theyOweUs: "They owe us",
    weOweThem: "We owe them",
    postedRecords: "Recorded transactions",
    loadingMoney: "Loading your money…",
    totalCurrency: "Total in this currency",
    moneyAtPlace: "Money at this place · open for details",
    noMoney:
      "No money has been recorded yet. Add opening money or record a transaction.",
    amountSource: "Where this amount came from",
    eachAmountSource: "Each amount is linked to a recorded transaction.",
    selectLocation: "Choose a place to see the transactions behind its amount.",
    recordedTransaction: "Recorded transaction",
    peopleTitle: "Customers & Sarafs",
    peopleIntro:
      "Find a person and see clearly whether they owe you or you owe them.",
    searchPeople: "Search customers or Sarafs",
    searchPeoplePlaceholder: "Name or phone",
    viewStatement: "View statement",
    noPeopleMatch: "No person matches this search.",
    statement: "Statement",
    balancesStaySeparate:
      "Each currency stays separate so the amount remains clear.",
    closeStatement: "Close statement",
    documents: "Identity documents",
    documentType: "Document type",
    tazkira: "Tazkira",
    passport: "Passport",
    customerPhoto: "Customer photo",
    preview: "Preview",
    due: "Due",
    captureUpload: "Take photo or upload",
    noDocuments: "No identity document has been added for this person.",
    balanceDetails: "Balance details",
    noOutstanding: "This person has no unpaid balance.",
    statementHistory: "History",
    noStatementHistory: "No activity has been recorded for this person.",
    transactionHistory: "Transaction history",
    transactionIntro:
      "See what happened, when it happened, and whether it was completed or corrected.",
    noTransactions:
      "No transactions yet. Use New transaction to record the first one.",
    correction: "CORRECTION",
    correctTransaction: "Correct a transaction",
    originalReference: "Original reference",
    correctionReason: "Why does this need correction?",
    submitCorrection: "Send correction request",
    ratesTitle: "Shop rates",
    ratesIntro:
      "Current approved buy and sell rates, with past changes kept for reference.",
    rateHistory: "Rate history",
    shopDefault: "Shop default",
    branchRate: "Branch rate",
    effectiveFrom: "Used from",
    noRateHistory: "No approved rate has been added yet.",
    calculatorNote:
      "The calculator is only a preview. A transaction is saved only when you confirm it.",
    reportsTitle: "Reports",
    reportsIntro: "Prepare profit, money, transaction, and customer reports.",
    from: "From",
    to: "To",
    all: "All",
    printA4: "Print A4",
    print58: "Print 58mm",
    print80: "Print 80mm",
    shareWhatsApp: "Share on WhatsApp",
    reportsReady: "matching transactions are ready for export.",
    noReportRows: "No transactions match these filters.",
    debtsTitle: "Debts",
    debtsIntro:
      "Record who owes you and who you owe, in the original currency.",
    choosePerson: "Choose a customer or Saraf",
    postDebt: "Save debt",
    posting: "Saving…",
    noDebts: "No unpaid debts. Add one only when money is actually owed.",
    settleDebt: "Record debt payment",
    remaining: "Remaining",
    paymentAmount: "Payment amount",
    savePayment: "Save payment",
    settlementNote:
      "Payments reduce the remaining amount and stay visible in the history.",
    cashboxTitle: "Check cashbox",
    cashboxIntro:
      "Compare the cash you counted with the amount SARAFI expects.",
    expected: "Expected",
    counted: "Counted",
    difference: "Difference",
    loading: "Loading…",
    differenceReason: "Reason for the difference",
    reasonRequired: "Explain any shortage or extra cash",
    submitCashCount: "Send cash count for review",
    cashDifferenceNote:
      "Any shortage or extra cash stays visible until an authorized person reviews it.",
    hawalaTitle: "Hawala",
    hawalaIntro:
      "Record the receiver, destination, amount, fee, and reference.",
    fullBeneficiaryName: "Receiver’s full name",
    cityCountry: "City or country",
    uniqueReference: "Unique reference",
    noHawala: "No Hawala transfer has been recorded yet.",
    compliance: "Compliance review",
    recentActivity: "Recent activity",
    traceable: "Every money movement is recorded and can be reviewed.",
    tradeReference: "Transaction",
    viewTradeDetails: "View transaction details",
    detailsAfterSync:
      "Transaction details will be available after the latest data loads.",
    couldNotLoad: "We could not load this information. Please try again.",
    couldNotSave:
      "We could not save this action. Check the details and try again.",
    savedSuccessfully: "Saved successfully.",
    businessSetupRequired:
      "Finish setting up the shop before saving this action.",
    activeBranchRequired: "Choose an active branch before saving this action.",
    activeCashboxRequired:
      "Choose an active cashbox before saving this action.",
    connectionRequired: "Reconnect to the internet before saving this action.",
    amountGreaterZero: "Enter an amount greater than zero.",
    exportUnavailable: "This report cannot be exported right now.",
    exportReady: "The report is ready.",
    reversed: "Corrected",
    requestFailed: "We could not complete this request. Please try again.",
    afghanAfghani: "Afghan Afghani",
    device: "Device",
    approved: "Approved",
    rejected: "Not approved",
    documentSaved: "Identity document saved securely.",
    shareOpened: "WhatsApp is ready to share this report.",
    direction: "Who owes whom?",
    person: "Customer or Saraf",
    counterparty: "Customer or Saraf",
    choosePersonFirst: "Choose a customer or Saraf before saving this debt.",
    settling: "Saving…",
    outstanding: "Remaining amount",
    expectedVsCounted: "Expected and counted cash",
    expectedAmount: "Expected amount",
    variance: "Difference",
    submitting: "Sending…",
    optionalSection: "OPTIONAL SERVICE",
    receiver: "Receiver",
    amountAfn: "Amount (AFN)",
    feeAfn: "Fee (AFN)",
    postingHawala: "Saving…",
    saveHawala: "Save Hawala",
    languageNameEnglish: "English",
    languageNameDari: "Dari",
    languageNamePashto: "Pashto",
    firstSetup: "FIRST SHOP SETUP",
    setupTitle: "Set up your Sarafi",
    setupIntro:
      "Start with the essential shop details. You can change advanced settings later.",
    businessNameQuestion: "What is your Sarafi called?",
    businessNamePlaceholder: "Sarwari Exchange",
    currenciesQuestion: "Which currencies do you use?",
    mainCashboxName: "Main cashbox name",
    mainCashboxPlaceholder: "Main Counter",
    startingCurrency: "Starting currency",
    selectedCurrencies: "Selected currencies",
    nextStep: "Next step",
    onboardingNext: "Add opening money, then record your first transaction",
    creatingBusiness: "Creating shop…",
    createBusiness: "Create my Sarafi",
    switchingShop: "MOVING EXISTING DATA",
    importCenter: "Import center",
    importIntro:
      "Check an import before any customer, opening-money, or debt record is saved.",
    importType: "What are you importing?",
    counterparties: "Customers and Sarafs",
    openingBalances: "Opening money",
    downloadTemplate: "Download CSV template",
    chooseCsv: "Choose CSV file",
    previewComplete: "File check complete. No records were changed.",
    csvReadFailed:
      "This CSV file could not be read. Check the template and try again.",
    rowsChecked: "Rows checked",
    issues: "Issues",
    readyToImport: "Ready to import",
    yes: "Yes",
    no: "No",
    total: "Total",
    row: "Row",
    fixRequired: "Fix required",
    importReady:
      "The checked file is ready. Confirm only if these records are correct.",
    confirmImport: "Confirm import",
    importSaved: "records imported successfully.",
    reviewTransaction: "Review transaction",
    confirmTransaction: "Confirm and save",
    editTransaction: "Edit transaction",
    confirmationTitle: "Check before saving",
    confirmationIntro:
      "Confirm that the shop gives and receives these exact amounts.",
    pairRateUnavailable:
      "No approved rate is available for this currency pair. Ask an authorized person to add the rate before exchanging.",
    addDebt: "Add debt",
    postingPaused: "Financial saving is paused until the connection returns.",
    retry: "Try again",
    sourceCurrency: "Calculator source currency",
    targetCurrency: "Calculator target currency",
    moreBusiness: "Reports, rates & cashboxes",
    moreTeam: "Employees, approvals & devices",
    moreSettings: "Shop & security settings",
    moreAdvanced: "Import, Hawala & compliance",
  },
  "fa-AF": {
    sarafiTagline: "دفتر دیجیتلی برای صرافی‌ها",
    owner: "مالک",
    cashier: "صندوق‌دار",
    manager: "مدیر",
    accountant: "محاسب",
    viewer: "بیننده",
    complianceOfficer: "مسئول بررسی",
    businessGroup: "صرافی",
    teamGroup: "کارمندان",
    settingsGroup: "تنظیمات",
    advancedGroup: "بخش پیشرفته",
    importData: "انتقال معلومات",
    connectionNotice: "معلومات صرافی شما وصل است",
    yourBusiness: "صرافی شما",
    assignedBranch: "شعبه تعیین‌شده",
    activeBranchSelected: "این شعبه فعال شما است.",
    signOut: "خروج",
    showAmounts: "نشان دادن مبالغ",
    hideAmounts: "پنهان کردن مبالغ",
    changeLanguage: "تغییر زبان",
    openHelp: "باز کردن راهنما",
    coreCashierActions: "کارهای روزمره صندوق‌دار",
    liveBuyRate: "نرخ فعلی خرید",
    liveSellRate: "نرخ فعلی فروش",
    liveRate: "نرخ فعلی",
    rateCalculator: "مبلغ برای محاسبه نرخ",
    businessDate: "تاریخ کاری",
    allTime: "همه زمان‌ها",
    status: "وضعیت",
    shopAction: "عملیات صرافی",
    income: "درآمد",
    ownerWithdrawal: "برداشت مالک",
    bankDeposit: "واریز به بانک",
    bankWithdrawal: "برداشت از بانک",
    rent: "کرایه",
    salary: "معاش",
    utilities: "آب و برق",
    internet: "انترنت",
    transport: "ترانسپورت",
    other: "سایر",
    reasonReference: "دلیل یا شماره مرجع",
    shopCheck: "سرافی پیش از ثبت، اجازه، صرافی و جزئیات پول را بررسی می‌کند.",
    helpIntro:
      "برای کارهای روزمره از فهرست اصلی استفاده کنید. عملیات پولی تنها پس از ورود و بررسی سرافی ثبت می‌شود.",
    openingBalance: "پول آغاز کار",
    recordOpeningMoney: "ثبت پول آغاز کار",
    startingAmount: "مبلغ همین اسعار",
    afnValue: "ارزش به افغانی",
    saveOpeningMoney: "ثبت پول آغاز کار",
    openingMoneyNote:
      "این بخش تنها برای پولی است که صرافی پیش از آغاز کار با سرافی داشت. این پول مفاد نیست.",
    backHome: "بازگشت به خانه",
    workspaceSection: "این بخش از فهرست اصلی در دسترس است.",
    transactionsDescription: "فعالیت ثبت‌شده و معاملات گذشته صرافی را ببینید.",
    moneyDescription: "مقدار پول هر اسعار و محل نگهداری آن را ببینید.",
    peopleDescription:
      "مشتریان و صرافان را پیدا کنید و ببینید چه کسی به چه کسی بدهکار است.",
    debtsDescription:
      "پولی را که مردم به شما بدهکار اند یا شما به آنان بدهکار هستید ثبت و بررسی کنید.",
    ratesDescription: "نرخ‌های مجاز خرید و فروش صرافی را ببینید.",
    reportsDescription: "گزارش تجارت، مفاد و معاملات را آماده کنید.",
    teamDescription: "کارمندان، دستگاه‌ها و تأییدها را مدیریت کنید.",
    settingsDescription: "صرافی، زبان‌ها، اسعار و امنیت را تنظیم کنید.",
    teamAccess: "دسترسی کارمندان",
    teamIntro:
      "ببینید چه کسی به صرافی دسترسی دارد، کدام دستگاه فعال است و چه چیزی تأیید می‌خواهد.",
    active: "فعال",
    suspended: "متوقف",
    accessOn: "دسترسی دارد",
    accessOff: "دسترسی ندارد",
    extraSecurityRequired: "امنیت اضافی ورود لازم است",
    normalSecurity: "امنیت عادی ورود",
    registeredDevices: "دستگاه‌های ثبت‌شده",
    lastSeen: "آخرین فعالیت",
    revoked: "لغوشده",
    approvalInbox: "درخواست‌های تأیید",
    approvalRequest: "درخواست تأیید",
    requested: "درخواست‌شده",
    review: "بررسی",
    noTeam: "هنوز کارمندی اضافه نشده است.",
    noDevices: "هنوز دستگاهی ثبت نشده است.",
    noApprovals: "درخواست تأییدی وجود ندارد.",
    selfApprovalRule: "هیچ‌کس نمی‌تواند درخواست خودش را تأیید کند.",
    accessRuleNote:
      "اجازه، شعبه، صندوق، دستگاه و تأیید هنگام ثبت هر عملیات خودکار بررسی می‌شود.",
    whereIsMoney: "پول من کجا است؟",
    moneyIntro:
      "پول را بر اساس اسعار و محل ببینید؛ هر مبلغ به معامله ثبت‌شده مربوط است.",
    allCurrencies: "همه اسعار",
    currencyFirst: "بر اساس اسعار",
    locationFirst: "بر اساس محل",
    printSnapshot: "چاپ این صفحه",
    theyOweUs: "آنها به ما بدهکار اند",
    weOweThem: "ما به آنها بدهکار هستیم",
    postedRecords: "معاملات ثبت‌شده",
    loadingMoney: "پول شما در حال بارگذاری است…",
    totalCurrency: "مجموع همین اسعار",
    moneyAtPlace: "پول در این محل · برای جزئیات باز کنید",
    noMoney: "هنوز پولی ثبت نشده است. پول آغاز کار یا یک معامله را ثبت کنید.",
    amountSource: "این مبلغ از کجا آمده است",
    eachAmountSource: "هر مبلغ به یک معامله ثبت‌شده مربوط است.",
    selectLocation:
      "یک محل را انتخاب کنید تا معاملات مربوط به مبلغ آن را ببینید.",
    recordedTransaction: "معامله ثبت‌شده",
    peopleTitle: "مشتریان و صرافان",
    peopleIntro:
      "یک شخص را پیدا کنید و روشن ببینید او به شما بدهکار است یا شما به او.",
    searchPeople: "جستجوی مشتری یا صراف",
    searchPeoplePlaceholder: "نام یا شماره تماس",
    viewStatement: "دیدن صورت‌حساب",
    noPeopleMatch: "شخصی با این جستجو پیدا نشد.",
    statement: "صورت‌حساب",
    balancesStaySeparate: "هر اسعار جدا نگهداری می‌شود تا مبلغ روشن بماند.",
    closeStatement: "بستن صورت‌حساب",
    documents: "اسناد هویتی",
    documentType: "نوع سند",
    tazkira: "تذکره",
    passport: "پاسپورت",
    customerPhoto: "عکس مشتری",
    preview: "دیدن",
    due: "سررسید",
    captureUpload: "عکس بگیرید یا بارگذاری کنید",
    noDocuments: "برای این شخص هنوز سند هویتی اضافه نشده است.",
    balanceDetails: "جزئیات طلب و بدهی",
    noOutstanding: "این شخص مبلغ پرداخت‌نشده ندارد.",
    statementHistory: "تاریخچه",
    noStatementHistory: "برای این شخص هنوز فعالیتی ثبت نشده است.",
    transactionHistory: "تاریخچه معاملات",
    transactionIntro: "ببینید چه کاری، چه زمانی و با چه وضعیتی انجام شده است.",
    noTransactions: "هنوز معامله‌ای ثبت نشده است. از «معامله جدید» آغاز کنید.",
    correction: "اصلاح",
    correctTransaction: "اصلاح یک معامله",
    originalReference: "شماره معامله اصلی",
    correctionReason: "چرا این معامله باید اصلاح شود؟",
    submitCorrection: "فرستادن درخواست اصلاح",
    ratesTitle: "نرخ‌های صرافی",
    ratesIntro: "نرخ فعلی مجاز خرید و فروش، همراه با تغییرات گذشته.",
    rateHistory: "تاریخچه نرخ",
    shopDefault: "نرخ عمومی صرافی",
    branchRate: "نرخ شعبه",
    effectiveFrom: "قابل استفاده از",
    noRateHistory: "هنوز نرخ مجازی اضافه نشده است.",
    calculatorNote:
      "محاسبه‌گر تنها پیش‌نمایش است. معامله فقط پس از تأیید شما ثبت می‌شود.",
    reportsTitle: "گزارش‌ها",
    reportsIntro: "گزارش مفاد، پول، معاملات و مشتریان را آماده کنید.",
    from: "از",
    to: "تا",
    all: "همه",
    printA4: "چاپ A4",
    print58: "چاپ ۵۸ میلی‌متر",
    print80: "چاپ ۸۰ میلی‌متر",
    shareWhatsApp: "فرستادن در واتس‌اپ",
    reportsReady: "معامله برای صدور آماده است.",
    noReportRows: "معامله‌ای با این فلترها پیدا نشد.",
    debtsTitle: "طلب و بدهی",
    debtsIntro:
      "ثبت کنید چه کسی به شما بدهکار است و شما به چه کسی بدهکار هستید.",
    choosePerson: "یک مشتری یا صراف را انتخاب کنید",
    postDebt: "ثبت قرض",
    posting: "در حال ثبت…",
    noDebts:
      "قرض پرداخت‌نشده وجود ندارد. تنها زمانی اضافه کنید که واقعاً پولی بدهکار باشد.",
    settleDebt: "ثبت پرداخت قرض",
    remaining: "باقی‌مانده",
    paymentAmount: "مبلغ پرداخت",
    savePayment: "ثبت پرداخت",
    settlementNote:
      "پرداخت، مبلغ باقی‌مانده را کم می‌کند و در تاریخچه باقی می‌ماند.",
    cashboxTitle: "بررسی صندوق",
    cashboxIntro: "پول شمارش‌شده را با مبلغ مورد انتظار سرافی مقایسه کنید.",
    expected: "مورد انتظار",
    counted: "شمارش‌شده",
    difference: "تفاوت",
    loading: "در حال بارگذاری…",
    differenceReason: "دلیل تفاوت",
    reasonRequired: "دلیل کمبود یا پول اضافی را بنویسید",
    submitCashCount: "فرستادن شمارش صندوق برای بررسی",
    cashDifferenceNote:
      "کمبود یا پول اضافی تا بررسی شخص مجاز روشن باقی می‌ماند.",
    hawalaTitle: "حواله",
    hawalaIntro: "گیرنده، مقصد، مبلغ، کمیشن و شماره مرجع را ثبت کنید.",
    fullBeneficiaryName: "نام کامل گیرنده",
    cityCountry: "شهر یا کشور",
    uniqueReference: "شماره مرجع یکتا",
    noHawala: "هنوز حواله‌ای ثبت نشده است.",
    compliance: "بررسی اصول کاری",
    recentActivity: "فعالیت اخیر",
    traceable: "هر حرکت پول ثبت می‌شود و قابل بررسی است.",
    tradeReference: "معامله",
    viewTradeDetails: "دیدن جزئیات معامله",
    detailsAfterSync:
      "جزئیات معامله پس از بارگذاری تازه‌ترین معلومات در دسترس می‌شود.",
    couldNotLoad: "این معلومات بارگذاری نشد. لطفاً دوباره کوشش کنید.",
    couldNotSave: "این عملیات ثبت نشد. جزئیات را بررسی و دوباره کوشش کنید.",
    savedSuccessfully: "با موفقیت ثبت شد.",
    businessSetupRequired: "پیش از ثبت این عملیات، تنظیم صرافی را تکمیل کنید.",
    activeBranchRequired: "پیش از ثبت این عملیات یک شعبه فعال انتخاب کنید.",
    activeCashboxRequired: "پیش از ثبت این عملیات یک صندوق فعال انتخاب کنید.",
    connectionRequired: "پیش از ثبت این عملیات دوباره به انترنت وصل شوید.",
    amountGreaterZero: "مبلغی بیشتر از صفر وارد کنید.",
    exportUnavailable: "در حال حاضر این گزارش صادر نمی‌شود.",
    exportReady: "گزارش آماده است.",
    reversed: "اصلاح‌شده",
    requestFailed: "این درخواست انجام نشد. لطفاً دوباره کوشش کنید.",
    afghanAfghani: "افغانی افغانستان",
    device: "دستگاه",
    approved: "تأییدشده",
    rejected: "تأییدنشده",
    documentSaved: "سند هویتی به‌گونه امن ثبت شد.",
    shareOpened: "واتس‌اپ برای فرستادن این گزارش آماده است.",
    direction: "چه کسی به چه کسی بدهکار است؟",
    person: "مشتری یا صراف",
    counterparty: "مشتری یا صراف",
    choosePersonFirst: "پیش از ثبت قرض یک مشتری یا صراف را انتخاب کنید.",
    settling: "در حال ثبت…",
    outstanding: "مبلغ باقی‌مانده",
    expectedVsCounted: "پول مورد انتظار و شمارش‌شده",
    expectedAmount: "مبلغ مورد انتظار",
    variance: "تفاوت",
    submitting: "در حال فرستادن…",
    optionalSection: "خدمت اختیاری",
    receiver: "گیرنده",
    amountAfn: "مبلغ (افغانی)",
    feeAfn: "کمیشن (افغانی)",
    postingHawala: "در حال ثبت…",
    saveHawala: "ثبت حواله",
    languageNameEnglish: "انگلیسی",
    languageNameDari: "دری",
    languageNamePashto: "پښتو",
    firstSetup: "تنظیم نخست صرافی",
    setupTitle: "صرافی خود را تنظیم کنید",
    setupIntro:
      "از معلومات ضروری صرافی آغاز کنید. تنظیمات پیشرفته را بعداً تغییر داده می‌توانید.",
    businessNameQuestion: "نام صرافی شما چیست؟",
    businessNamePlaceholder: "صرافی سروری",
    currenciesQuestion: "از کدام اسعار استفاده می‌کنید؟",
    mainCashboxName: "نام صندوق اصلی",
    mainCashboxPlaceholder: "صندوق اصلی",
    startingCurrency: "اسعار اصلی",
    selectedCurrencies: "اسعار انتخاب‌شده",
    nextStep: "گام بعدی",
    onboardingNext: "پول آغاز کار را اضافه و سپس نخستین معامله را ثبت کنید",
    creatingBusiness: "صرافی در حال ساخت است…",
    createBusiness: "ساختن صرافی من",
    switchingShop: "انتقال معلومات قبلی",
    importCenter: "مرکز انتقال معلومات",
    importIntro:
      "پیش از ثبت مشتریان، پول آغاز کار یا قرض‌ها، فایل را بررسی کنید.",
    importType: "چه معلوماتی را انتقال می‌دهید؟",
    counterparties: "مشتریان و صرافان",
    openingBalances: "پول آغاز کار",
    downloadTemplate: "دانلود نمونه CSV",
    chooseCsv: "انتخاب فایل CSV",
    previewComplete: "بررسی فایل تمام شد. هیچ معلوماتی تغییر نکرد.",
    csvReadFailed:
      "این فایل CSV خوانده نشد. نمونه را بررسی و دوباره کوشش کنید.",
    rowsChecked: "ردیف‌های بررسی‌شده",
    issues: "مشکلات",
    readyToImport: "آماده انتقال",
    yes: "بلی",
    no: "نخیر",
    total: "مجموع",
    row: "ردیف",
    fixRequired: "اصلاح لازم است",
    importReady:
      "فایل بررسی‌شده آماده است. تنها در صورت درستی معلومات تأیید کنید.",
    confirmImport: "تأیید انتقال",
    importSaved: "مورد با موفقیت انتقال شد.",
    reviewTransaction: "بررسی معامله",
    confirmTransaction: "تأیید و ثبت",
    editTransaction: "اصلاح معامله",
    confirmationTitle: "پیش از ثبت بررسی کنید",
    confirmationIntro:
      "تأیید کنید که صرافی دقیقاً همین مبالغ را می‌دهد و دریافت می‌کند.",
    pairRateUnavailable:
      "برای این جفت اسعار نرخ تأییدشده موجود نیست. پیش از تبادله از مسئول اجازه‌دار بخواهید نرخ را ثبت کند.",
    addDebt: "ثبت قرض",
    postingPaused: "ثبت عملیات مالی تا برگشت انترنت متوقف است.",
    retry: "کوشش دوباره",
    sourceCurrency: "اسعار مبدأ محاسبه‌گر",
    targetCurrency: "اسعار مقصد محاسبه‌گر",
    moreBusiness: "گزارش‌ها، نرخ‌ها و صندوق‌ها",
    moreTeam: "کارمندان، تأییدها و دستگاه‌ها",
    moreSettings: "تنظیمات صرافی و امنیت",
    moreAdvanced: "انتقال معلومات، حواله و بررسی",
  },
  "ps-AF": {
    sarafiTagline: "د صرافیو لپاره ډیجیټلي دفتر",
    owner: "مالک",
    cashier: "صندوق‌دار",
    manager: "مدیر",
    accountant: "محاسب",
    viewer: "کتونکی",
    complianceOfficer: "د څارنې مسئول",
    businessGroup: "صرافي",
    teamGroup: "کارکوونکي",
    settingsGroup: "امستنې",
    advancedGroup: "پرمختللې برخه",
    importData: "معلومات لېږدول",
    connectionNotice: "ستاسو د صرافۍ معلومات نښتي دي",
    yourBusiness: "ستاسو صرافي",
    assignedBranch: "ټاکل شوې څانګه",
    activeBranchSelected: "دا ستاسو فعاله څانګه ده.",
    signOut: "وتل",
    showAmounts: "مبلغونه ښودل",
    hideAmounts: "مبلغونه پټول",
    changeLanguage: "ژبه بدلول",
    openHelp: "لارښود پرانیستل",
    coreCashierActions: "د صندوق‌دار ورځني کارونه",
    liveBuyRate: "د پېرود اوسنی نرخ",
    liveSellRate: "د پلور اوسنی نرخ",
    liveRate: "اوسنی نرخ",
    rateCalculator: "د نرخ د محاسبې مبلغ",
    businessDate: "کاري نېټه",
    allTime: "ټول وخت",
    status: "حالت",
    shopAction: "د صرافۍ کړنه",
    income: "عاید",
    ownerWithdrawal: "د مالک ایستل",
    bankDeposit: "بانک ته جمع کول",
    bankWithdrawal: "له بانک څخه ایستل",
    rent: "کرایه",
    salary: "معاش",
    utilities: "اوبه او برېښنا",
    internet: "انټرنېټ",
    transport: "ترانسپورټ",
    other: "نور",
    reasonReference: "دلیل یا د حوالې شمېره",
    shopCheck: "صرافي له ثبتولو مخکې اجازه، کاروبار او د پیسو معلومات ګوري.",
    helpIntro:
      "د ورځنیو کارونو لپاره اصلي لېست وکاروئ. مالي کړنه یوازې له ننوتلو او د صرافي له تایید وروسته ثبتېږي.",
    openingBalance: "پیل پیسې",
    recordOpeningMoney: "پیل پیسې ثبتول",
    startingAmount: "د همدې اسعارو مبلغ",
    afnValue: "په افغانۍ ارزښت",
    saveOpeningMoney: "پیل پیسې ثبتول",
    openingMoneyNote:
      "دا برخه یوازې د هغو پیسو لپاره ده چې صرافۍ د سرافي له کارولو مخکې لرلې. دا پیسې ګټه نه ده.",
    backHome: "کور ته ستنېدل",
    workspaceSection: "دا برخه له اصلي لېست څخه موندل کېږي.",
    transactionsDescription: "د صرافۍ ثبت شوی فعالیت او پخوانۍ معاملې وګورئ.",
    moneyDescription: "په هر اسعار کې د خپلو پیسو اندازه او ځای وګورئ.",
    peopleDescription:
      "پېرودونکي او صرافان ومومئ او وګورئ چې څوک د چا پوروړی دی.",
    debtsDescription:
      "هغه پیسې ثبت او وګورئ چې خلک یې تاسو ته یا تاسو یې هغوی ته پوروړي یاست.",
    ratesDescription: "د صرافۍ مجاز د پېرود او پلور نرخونه وګورئ.",
    reportsDescription: "د کاروبار، ګټې او معاملو راپورونه چمتو کړئ.",
    teamDescription: "کارکوونکي، وسایل او تاییدونه اداره کړئ.",
    settingsDescription: "صرافي، ژبې، اسعار او امنیت تنظیم کړئ.",
    teamAccess: "د کارکوونکو لاسرسی",
    teamIntro:
      "وګورئ څوک صرافۍ ته لاسرسی لري، کوم وسایل فعال دي او څه تایید غواړي.",
    active: "فعال",
    suspended: "ځنډول شوی",
    accessOn: "لاس‌رسی لري",
    accessOff: "لاس‌رسی نه لري",
    extraSecurityRequired: "د ننوتلو اضافي امنیت اړین دی",
    normalSecurity: "د ننوتلو عادي امنیت",
    registeredDevices: "ثبت شوي وسایل",
    lastSeen: "وروستی فعالیت",
    revoked: "لغوه شوی",
    approvalInbox: "د تایید غوښتنې",
    approvalRequest: "د تایید غوښتنه",
    requested: "غوښتل شوی",
    review: "کتنه",
    noTeam: "تر اوسه کارکوونکی نه دی ورزیات شوی.",
    noDevices: "تر اوسه وسیله نه ده ثبت شوې.",
    noApprovals: "د تایید غوښتنه نشته.",
    selfApprovalRule: "هیڅوک خپله غوښتنه نه شي تاییدولی.",
    accessRuleNote:
      "د اجازې، څانګې، صندوق، وسیلې او تایید قواعد د هر ثبت پر مهال په خپله کتل کېږي.",
    whereIsMoney: "زما پیسې چېرته دي؟",
    moneyIntro:
      "پیسې د اسعارو او ځای له مخې وګورئ؛ هر مبلغ له ثبت شوې معاملې سره تړلی دی.",
    allCurrencies: "ټول اسعار",
    currencyFirst: "د اسعارو له مخې",
    locationFirst: "د ځای له مخې",
    printSnapshot: "دا مخ چاپول",
    theyOweUs: "هغوی زموږ پوروړي دي",
    weOweThem: "موږ د هغوی پوروړي یو",
    postedRecords: "ثبت شوې معاملې",
    loadingMoney: "ستاسو پیسې لوډېږي…",
    totalCurrency: "د همدې اسعارو ټول مبلغ",
    moneyAtPlace: "په دې ځای کې پیسې · د جزیاتو لپاره یې پرانیزئ",
    noMoney: "تر اوسه پیسې نه دي ثبت شوې. پیل پیسې یا یوه معامله ثبت کړئ.",
    amountSource: "دا مبلغ له کومه راغلی",
    eachAmountSource: "هر مبلغ له یوې ثبت شوې معاملې سره تړلی دی.",
    selectLocation: "یو ځای وټاکئ چې د هغه د مبلغ اړوند معاملې وګورئ.",
    recordedTransaction: "ثبت شوې معامله",
    peopleTitle: "پېرودونکي او صرافان",
    peopleIntro:
      "یو کس ومومئ او په روښانه ډول وګورئ چې هغه ستاسو پوروړی دی که تاسو د هغه.",
    searchPeople: "پېرودونکی یا صراف ولټوئ",
    searchPeoplePlaceholder: "نوم یا د ټیلیفون شمېره",
    viewStatement: "حساب کتل",
    noPeopleMatch: "له دې لټون سره څوک ونه موندل شو.",
    statement: "حساب",
    balancesStaySeparate: "هر اسعار جلا ساتل کېږي چې مبلغ روښانه پاتې شي.",
    closeStatement: "حساب تړل",
    documents: "د پېژندنې اسناد",
    documentType: "د سند ډول",
    tazkira: "تذکره",
    passport: "پاسپورټ",
    customerPhoto: "د پېرودونکي عکس",
    preview: "کتل",
    due: "د ورکړې نېټه",
    captureUpload: "عکس واخلئ یا پورته یې کړئ",
    noDocuments: "د دې کس لپاره د پېژندنې سند نه دی ورزیات شوی.",
    balanceDetails: "د پور جزیات",
    noOutstanding: "دا کس نه‌ورکړل شوی پور نه لري.",
    statementHistory: "تاریخچه",
    noStatementHistory: "د دې کس لپاره فعالیت نه دی ثبت شوی.",
    transactionHistory: "د معاملو تاریخچه",
    transactionIntro: "وګورئ څه، کله او په کوم حالت کې ترسره شوي دي.",
    noTransactions:
      "تر اوسه معامله نه ده ثبت شوې. له «نوې معامله» څخه پیل وکړئ.",
    correction: "سمون",
    correctTransaction: "معامله سمول",
    originalReference: "د اصلي معاملې شمېره",
    correctionReason: "ولې دا معامله سمون غواړي؟",
    submitCorrection: "د سمون غوښتنه لېږل",
    ratesTitle: "د صرافۍ نرخونه",
    ratesIntro: "د پېرود او پلور اوسني مجاز نرخونه او پخواني بدلونونه.",
    rateHistory: "د نرخ تاریخچه",
    shopDefault: "د صرافۍ عمومي نرخ",
    branchRate: "د څانګې نرخ",
    effectiveFrom: "له دې وخته کارول شوی",
    noRateHistory: "تر اوسه مجاز نرخ نه دی ورزیات شوی.",
    calculatorNote:
      "محاسبه‌ګر یوازې مخکتنه ده. معامله یوازې ستاسو له تایید وروسته ثبتېږي.",
    reportsTitle: "راپورونه",
    reportsIntro: "د ګټې، پیسو، معاملو او پېرودونکو راپورونه چمتو کړئ.",
    from: "له",
    to: "تر",
    all: "ټول",
    printA4: "A4 چاپ",
    print58: "۵۸ ملي‌متر چاپ",
    print80: "۸۰ ملي‌متر چاپ",
    shareWhatsApp: "په واټس‌اپ کې لېږل",
    reportsReady: "معاملې د صادرولو لپاره چمتو دي.",
    noReportRows: "له دې فلټرونو سره معامله ونه موندل شوه.",
    debtsTitle: "پورونه",
    debtsIntro: "ثبت کړئ چې څوک ستاسو پوروړی دی او تاسو د چا پوروړي یاست.",
    choosePerson: "یو پېرودونکی یا صراف وټاکئ",
    postDebt: "پور ثبتول",
    posting: "ثبتېږي…",
    noDebts:
      "نه‌ورکړل شوی پور نشته. یوازې هغه وخت یې ورزیات کړئ چې رښتیا پور وي.",
    settleDebt: "د پور ورکړه ثبتول",
    remaining: "پاتې",
    paymentAmount: "د ورکړې مبلغ",
    savePayment: "ورکړه ثبتول",
    settlementNote: "ورکړه پاتې مبلغ کموي او په تاریخچه کې ښکاري.",
    cashboxTitle: "صندوق کتل",
    cashboxIntro: "شمېرل شوې نغدې د صرافي له تمه شوي مبلغ سره پرتله کړئ.",
    expected: "تمه شوی",
    counted: "شمېرل شوی",
    difference: "توپیر",
    loading: "لوډېږي…",
    differenceReason: "د توپیر دلیل",
    reasonRequired: "د کمو یا زیاتو پیسو دلیل ولیکئ",
    submitCashCount: "د صندوق شمېر د کتنې لپاره لېږل",
    cashDifferenceNote:
      "کمې یا زیاتې پیسې د مجاز کس تر کتنې پورې ښکاره پاتې کېږي.",
    hawalaTitle: "حواله",
    hawalaIntro: "د پیسو اخیستونکی، ځای، مبلغ، کمېشن او د حوالې شمېره ثبت کړئ.",
    fullBeneficiaryName: "د اخیستونکي بشپړ نوم",
    cityCountry: "ښار یا هېواد",
    uniqueReference: "ځانګړې حواله شمېره",
    noHawala: "تر اوسه حواله نه ده ثبت شوې.",
    compliance: "د اصولو کتنه",
    recentActivity: "وروستی فعالیت",
    traceable: "د پیسو هر حرکت ثبتېږي او د کتنې وړ وي.",
    tradeReference: "معامله",
    viewTradeDetails: "د معاملې جزیات کتل",
    detailsAfterSync:
      "د معاملې جزیات د تازه معلوماتو له لوډېدو وروسته موندل کېږي.",
    couldNotLoad: "دا معلومات لوډ نه شول. بیا هڅه وکړئ.",
    couldNotSave: "دا کړنه ثبت نه شوه. معلومات وګورئ او بیا هڅه وکړئ.",
    savedSuccessfully: "په بریالیتوب ثبت شو.",
    businessSetupRequired: "د دې کړنې له ثبتولو مخکې د صرافۍ امستنې بشپړې کړئ.",
    activeBranchRequired: "د دې کړنې له ثبتولو مخکې فعاله څانګه وټاکئ.",
    activeCashboxRequired: "د دې کړنې له ثبتولو مخکې فعال صندوق وټاکئ.",
    connectionRequired: "د دې کړنې له ثبتولو مخکې انټرنېټ سره بیا ونښلئ.",
    amountGreaterZero: "له صفر څخه لوی مبلغ ولیکئ.",
    exportUnavailable: "دا راپور اوس نه شي صادرېدای.",
    exportReady: "راپور چمتو دی.",
    reversed: "سمون شوی",
    requestFailed: "دا غوښتنه بشپړه نه شوه. بیا هڅه وکړئ.",
    afghanAfghani: "افغانۍ",
    device: "وسیله",
    approved: "تایید شوی",
    rejected: "نه دی تایید شوی",
    documentSaved: "د پېژندنې سند په خوندي ډول ثبت شو.",
    shareOpened: "واټس‌اپ د دې راپور لېږلو ته چمتو دی.",
    direction: "څوک د چا پوروړی دی؟",
    person: "پېرودونکی یا صراف",
    counterparty: "پېرودونکی یا صراف",
    choosePersonFirst: "د پور له ثبتولو مخکې پېرودونکی یا صراف وټاکئ.",
    settling: "ثبتېږي…",
    outstanding: "پاتې مبلغ",
    expectedVsCounted: "تمه شوې او شمېرل شوې پیسې",
    expectedAmount: "تمه شوی مبلغ",
    variance: "توپیر",
    submitting: "لېږل کېږي…",
    optionalSection: "اختیاري خدمت",
    receiver: "اخیستونکی",
    amountAfn: "مبلغ (افغانۍ)",
    feeAfn: "کمېشن (افغانۍ)",
    postingHawala: "ثبتېږي…",
    saveHawala: "حواله ثبتول",
    languageNameEnglish: "انګلیسي",
    languageNameDari: "دري",
    languageNamePashto: "پښتو",
    firstSetup: "د صرافۍ لومړنۍ امستنې",
    setupTitle: "خپله صرافي جوړه کړئ",
    setupIntro:
      "د صرافۍ له اړینو معلوماتو پیل وکړئ. پرمختللې امستنې وروسته بدلولی شئ.",
    businessNameQuestion: "ستاسو د صرافۍ نوم څه دی؟",
    businessNamePlaceholder: "سروري صرافي",
    currenciesQuestion: "کوم اسعار کاروئ؟",
    mainCashboxName: "د اصلي صندوق نوم",
    mainCashboxPlaceholder: "اصلي صندوق",
    startingCurrency: "اصلي اسعار",
    selectedCurrencies: "ټاکل شوي اسعار",
    nextStep: "بل ګام",
    onboardingNext: "پیل پیسې ورزیاتې او بیا خپله لومړۍ معامله ثبت کړئ",
    creatingBusiness: "صرافي جوړېږي…",
    createBusiness: "زما صرافي جوړول",
    switchingShop: "پخواني معلومات لېږدول",
    importCenter: "د معلوماتو د لېږد مرکز",
    importIntro: "د پېرودونکو، پیل پیسو یا پورونو له ثبتولو مخکې فایل وګورئ.",
    importType: "کوم معلومات لېږدوئ؟",
    counterparties: "پېرودونکي او صرافان",
    openingBalances: "پیل پیسې",
    downloadTemplate: "د CSV نمونه ښکته کول",
    chooseCsv: "CSV فایل ټاکل",
    previewComplete: "د فایل کتنه بشپړه شوه. معلومات نه دي بدل شوي.",
    csvReadFailed: "دا CSV فایل ونه لوستل شو. نمونه وګورئ او بیا هڅه وکړئ.",
    rowsChecked: "کتل شوي کتارونه",
    issues: "ستونزې",
    readyToImport: "لېږد ته چمتو",
    yes: "هو",
    no: "نه",
    total: "ټول",
    row: "کتار",
    fixRequired: "سمون اړین دی",
    importReady:
      "کتل شوی فایل چمتو دی. یوازې د معلوماتو له ډاډ وروسته یې تایید کړئ.",
    confirmImport: "لېږد تاییدول",
    importSaved: "توکي په بریالیتوب ولېږدول شول.",
    reviewTransaction: "معامله کتل",
    confirmTransaction: "تایید او ثبتول",
    editTransaction: "معامله سمول",
    confirmationTitle: "له ثبتولو مخکې یې وګورئ",
    confirmationIntro: "تایید کړئ چې صرافي همدا مبلغونه ورکوي او ترلاسه کوي.",
    pairRateUnavailable:
      "د دې اسعارو جوړې لپاره تایید شوی نرخ نشته. له تبادلې مخکې له واک لرونکي کس څخه وغواړئ چې نرخ ثبت کړي.",
    addDebt: "پور ثبتول",
    postingPaused: "د انټرنېټ تر بېرته راتګ پورې مالي ثبت درول شوی.",
    retry: "بیا هڅه",
    sourceCurrency: "د محاسبې اصلي اسعار",
    targetCurrency: "د محاسبې ترلاسه کېدونکي اسعار",
    moreBusiness: "راپورونه، نرخونه او صندوقونه",
    moreTeam: "کارکوونکي، تاییدونه او وسایل",
    moreSettings: "د صرافۍ او امنیت امستنې",
    moreAdvanced: "معلومات لېږدول، حواله او څارنه",
  },
} as const;

export type UxCopyKey = keyof typeof copy.en;

export function ux(language: Language, key: UxCopyKey): string {
  return copy[language][key] ?? copy.en[key];
}
