import type { Language } from "./i18n";

const copy = {
  en: {
    sarafiTagline: "Digital daftar for Sarafi shops",
    openingLabel: "SARAFI opening screen",
    skipOpening: "Skip",
    owner: "Owner",
    cashier: "Cashier",
    manager: "Manager",
    accountant: "Accountant",
    viewer: "Viewer",
    complianceOfficer: "Compliance officer",
    businessGroup: "Business",
    teamGroup: "Team",
    settingsGroup: "Settings",
    advancedGroup: "Advanced",
    importData: "Import data",
    connectionNotice: "Your shop data is connected",
    yourBusiness: "Your business",
    assignedBranch: "Assigned branch",
    activeBranchSelected: "This is your active branch.",
    signOut: "Sign out",
    showAmounts: "Show amounts",
    hideAmounts: "Hide amounts",
    changeLanguage: "Change language",
    openHelp: "Open help",
    coreCashierActions: "Daily cashier actions",
    startTransaction: "Record a new transaction",
    chooseDailyAction:
      "Choose what happened. SARAFI will guide you through the remaining steps.",
    readOnlyRoleNotice:
      "This access is for review only. Ask the owner for permission if you need to record or change money.",
    liveBuyRate: "Current buy rate",
    liveSellRate: "Current sell rate",
    liveRate: "Current rate",
    rateCalculator: "Rate calculator amount",
    businessDate: "Business date",
    allTime: "All time",
    status: "Status",
    shopAction: "SHOP ACTION",
    income: "Income",
    ownerWithdrawal: "Owner withdrawal",
    bankDeposit: "Bank deposit",
    bankWithdrawal: "Bank withdrawal",
    rent: "Rent",
    salary: "Salary",
    utilities: "Utilities",
    internet: "Internet",
    transport: "Transport",
    other: "Other",
    reasonReference: "Reason or reference",
    shopCheck:
      "SARAFI checks your access, shop, and money details before saving this action.",
    helpIntro:
      "Use the main menu to move between daily shop tasks. Financial actions are saved only after you sign in and SARAFI verifies them.",
    openingBalance: "Opening money",
    recordOpeningMoney: "Record opening money",
    startingAmount: "Amount in this currency",
    afnValue: "Value in AFN",
    saveOpeningMoney: "Save opening money",
    openingMoneyNote:
      "Use this only for money the shop already had before starting SARAFI. It is not profit.",
    backHome: "Back to Home",
    workspaceSection: "This section is available from the main menu.",
    transactionsDescription:
      "Review recorded shop activity and past transactions.",
    moneyDescription:
      "See how much money you have in each currency and where it is kept.",
    peopleDescription: "Find customers and Sarafs, and see who owes whom.",
    debtsDescription:
      "Record and review money people owe you and money you owe them.",
    ratesDescription: "See the shop’s approved buy and sell rates.",
    reportsDescription: "Prepare business, profit, and transaction reports.",
    teamDescription: "Manage employees, devices, and approvals.",
    settingsDescription:
      "Manage your shop, languages, currencies, and security.",
    teamAccess: "Team access",
    teamIntro:
      "See who can use the shop, which devices are active, and what needs approval.",
    previewOwnerName: "Shop owner",
    previewCashierName: "Main cashier",
    previewCashboxName: "Main Counter",
    previewSafeName: "Main Safe",
    previewBankName: "Main Bank Account",
    previewBankReference: "Ending 1234",
    moneyAccountsTitle: "Money accounts",
    moneyAccountsIntro: "Create each real place where money is kept once. During a transaction, simply choose where the money comes from and where it goes.",
    addMoneyAccount: "Add money account",
    accountName: "Account name",
    accountNamePlaceholder: "Example: Main safe or Azizi Bank",
    accountType: "Account type",
    accountReference: "Short reference (optional)",
    accountReferencePlaceholder: "Example: Account ending 1234",
    accountType_cashbox: "Cashbox",
    accountType_safe: "Safe",
    accountType_bank: "Bank account",
    accountType_mobile_money: "Mobile wallet",
    accountType_partner: "Partner account",
    accountType_other: "Other account",
    saveMoneyAccount: "Save account",
    accountCreated: "Money account added.",
    accountCreateFailed: "The money account could not be added. Check the name and try again.",
    noMoneyInAccount: "No money recorded here yet",
    noMoneyAccounts: "No money account is ready. The owner must add one before daily transactions can be saved.",
    ownerOnlyAccounts: "Only the owner can add or change money accounts. Employees can use only the accounts assigned to them.",
    shopCurrenciesTitle: "Currencies used by this shop",
    shopCurrenciesIntro: "The global catalog is available. Turn on only the currencies your shop actually buys, sells, receives, or pays.",
    enabledCurrencies: "Currencies ready to use",
    manageCurrencies: "Manage currencies",
    manageCurrenciesIntro:
      "Owner setup: search the world catalog and turn currencies on or off.",
    baseCurrency: "Base currency",
    searchCurrency: "Find a currency",
    searchCurrencyPlaceholder: "Code or name, for example CNY",
    usedInShop: "used by this shop",
    currencyOwnerHelp: "The owner controls this list. Enabling a currency makes it available in daily forms; exchange still requires an approved rate.",
    ownerOnlyCurrencies: "Only the owner can change the shop currency list.",
    currencyUpdated: "Shop currencies updated.",
    currencyUpdateFailed: "This currency change could not be saved. A currency with money remaining cannot be turned off.",
    addWorldCurrency: "Add another world currency",
    chooseWorldCurrency: "Choose from the global currency catalog",
    sourceAccount: "Money comes from",
    destinationAccount: "Money goes to",
    chooseMoneyAccount: "Choose a money account",
    chooseSourceAccount: "Choose the source account",
    chooseDestinationAccount: "Choose the destination account",
    accountsMustDiffer: "Choose two different accounts for this transfer.",
    valueInBaseCurrency: "Value in AFN",
    baseValueHelp: "Enter the AFN value used in the books. Currencies are never added together without a value.",
    customerOutside: "Customer or outside party",
    outsideAccount: "Outside account",
    openingFundsSource: "Opening funds",
    incomeSource: "Income source",
    expenseDestination: "Expense",
    ownerPersonal: "Owner's personal money",
    activeCashboxAccount: "Active cashbox",
    tradeMoneyFlow: "Accounts used in this transaction",
    tradeHasTwoMoneySides: "The foreign currency and AFN move in opposite directions. Both sides are recorded in the selected cashbox.",
    noCurrentRate: "No current rate",
    setShopRate: "Set an approved shop rate",
    setShopRateIntro: "Enter how many AFN equal one unit of the selected currency. The previous rate stays in history.",
    foreignCurrency: "Foreign currency",
    ratePerUnitPlaceholder: "AFN for 1 unit",
    saveShopRate: "Save approved rate",
    ownerOnlyRates: "Only the owner can set an approved exchange rate.",
    rateSaved: "The approved rate was saved.",
    rateSaveFailed: "The rate could not be saved. Enable both currencies and check the values.",
    addEmployee: "Add employee",
    addEmployeeIntro: "Invite a team member and choose exactly where they can work.",
    fullName: "Full name",
    workEmail: "Work email",
    employeeRole: "Job role",
    branchAccess: "Allowed branches",
    cashboxAccess: "Allowed cashboxes",
    businessWideAccess: "This role works across the business.",
    cashierScopeRequired: "Choose at least one branch and one cashbox for a cashier.",
    sendInvite: "Create invitation",
    sendingInvite: "Creating invitation…",
    pendingInvitations: "Pending invitations",
    noPendingInvites: "There are no pending invitations.",
    inviteCreated: "Invitation ready",
    inviteLinkInstructions: "Copy this private link and send it to the employee. It expires in 72 hours.",
    copyInviteLink: "Copy invitation link",
    linkCopied: "Invitation link copied.",
    emailInvite: "Send by email",
    expires: "Expires",
    cancelInvite: "Cancel invitation",
    editAccess: "Edit access",
    saveAccess: "Save access",
    suspendAccess: "Suspend access",
    reactivateAccess: "Restore access",
    accessChangeReason: "Reason for this change",
    cancelAction: "Cancel",
    assignedTo: "Assigned to",
    noSpecificScope: "Business-wide access",
    memberSince: "Joined",
    invited: "Invited",
    secureTeamAction: "Confirm this secure action",
    secureTeamIntro: "Team access changes require two-step sign-in. This protects your shop if a password is stolen.",
    setupAuthenticator: "Set up authenticator",
    authenticatorInstructions: "Scan this code in an authenticator app, then enter the six-digit code.",
    authenticatorSecret: "Manual setup code",
    verificationCode: "Six-digit code",
    verifySecurity: "Verify and continue",
    verifyingSecurity: "Verifying…",
    securityVerified: "Secure action confirmed.",
    mfaSetupFailed: "Authenticator setup could not be started. Please try again.",
    mfaVerificationFailed: "That verification code was not accepted. Check the code and try again.",
    teamLoadFailed: "Team information could not be loaded.",
    teamSaveFailed: "The team change could not be saved. Check the details and try again.",
    joinTeam: "Join your Sarafi team",
    joinTeamSubtitle: "Sign in or create an account with the email address that received this invitation.",
    createAndJoin: "Create account and join",
    invitationAccepted: "Invitation accepted. Your assigned workspace is ready.",
    invitationInvalid: "This invitation link is invalid or is no longer available.",
    invitationExpired: "This invitation has expired. Ask the owner for a new invitation.",
    invitationWrongAccount: "Use the same email address that the owner invited.",
    signOutDifferentAccount: "Sign out and use another account",
    active: "Active",
    suspended: "Suspended",
    accessOn: "Access on",
    accessOff: "Access off",
    extraSecurityRequired: "Extra sign-in security required",
    normalSecurity: "Normal sign-in security",
    registeredDevices: "Registered devices",
    lastSeen: "Last seen",
    revoked: "Revoked",
    approvalInbox: "Approval requests",
    approvalRequest: "Approval request",
    requested: "Requested",
    review: "Review",
    noTeam: "No employees have been added yet.",
    noDevices: "No devices have been registered yet.",
    deviceLinkFailed: "This browser could not be linked. Try again before saving a transaction.",
    previewCustomer: "Walk-in customer",
    platformAdministrator: "Platform administrator",
    platformAdministratorSignIn: "Use the separate administrator account. Business owners and employees sign in on the main page.",
    planPayment: "Plan & payment",
    addCustomer: "Add customer",
    customerName: "Customer or Saraf name",
    customerType: "Type",
    customerTypeCustomer: "Customer",
    customerTypeSaraf: "Saraf",
    customerTypeHawala: "Hawala partner",
    customerTypeSupplier: "Supplier",
    customerTypeEmployee: "Employee",
    phoneOptional: "Phone (optional)",
    saveCustomer: "Save customer",
    customerCreated: "Customer saved and ready to use.",
    customerCreateFailed: "The customer could not be saved. Check the name and try again.",
    deviceAwaitingOwner: "This browser is linked but waiting for the owner’s approval. You can look around now; saving money movements opens after approval.",
    deviceTrusted: "Approved",
    deviceWaiting: "Waiting for approval",
    deviceControlIntro: "Approve a worker’s new browser before it can save money movements. Revoke a lost or shared browser immediately.",
    deviceReasonRequired: "Write a short reason for this device change.",
    deviceReasonPlaceholder: "Example: Counter computer checked",
    approveDevice: "Approve device",
    revokeDevice: "Revoke device",
    deviceApproved: "The device is approved and ready.",
    deviceRevoked: "The device was revoked.",
    moneyPlacesCount: "money places",
    roleHomeTitle_owner: "Owner control center",
    roleHomeDescription_owner: "See the whole business, supervise people and devices, and keep payments and controls in one place.",
    roleHomeTitle_manager: "Daily operations",
    roleHomeDescription_manager: "Run the branches, review work, and approve operational actions without changing owner-only settings.",
    roleHomeTitle_accountant: "Accounts and reports",
    roleHomeDescription_accountant: "Review balances, reports, and cash checks. This role cannot save money movements.",
    roleHomeTitle_cashier: "My counter today",
    roleHomeDescription_cashier: "Buy, sell, receive, pay, and close only the counter assigned to you.",
    roleHomeTitle_compliance_officer: "Compliance review",
    roleHomeDescription_compliance_officer: "Review customer checks, alerts, cases, and required records without posting transactions.",
    roleHomeTitle_viewer: "Read-only review",
    roleHomeDescription_viewer: "View approved balances, reports, and transaction history without changing records.",
    customerLabel: "Customer",
    employeeLabel: "Employee",
    teamMember: "Team member",
    weGaveLabel: "We gave",
    weReceivedLabel: "We received",
    confirmPassword: "Confirm password",
    fullNameRequired: "Enter your full name.",
    passwordsDoNotMatch: "The two passwords do not match.",
    ownerSignupOnly: "Creating a new Sarafi business",
    workerUsesInvite: "Only the owner starts a new business here. Employees create or use their account from the owner’s invitation link.",
    everyoneSignsInHere: "Owner, manager, cashier, accountant, compliance, and viewer",
    signInRoleAutomatic: "Everyone signs in here. SARAFI opens only the job, branch, and cashbox assigned to that account.",
    cashierCloseShortcut: "Close my counter",
    noApprovals: "There are no approval requests.",
    selfApprovalRule: "One person cannot approve their own request.",
    accessRuleNote:
      "Access, branch, cashbox, device, and approval rules are checked automatically when an action is saved.",
    whereIsMoney: "Where is my money?",
    moneyIntro:
      "Money by currency and place, with every amount linked to a recorded transaction.",
    allCurrencies: "All currencies",
    currencyFirst: "By currency",
    locationFirst: "By location",
    printSnapshot: "Print this view",
    theyOweUs: "They owe us",
    weOweThem: "We owe them",
    postedRecords: "Recorded transactions",
    loadingMoney: "Loading your money…",
    totalCurrency: "Total in this currency",
    moneyAtPlace: "Money at this place · open for details",
    noMoney:
      "No money has been recorded yet. Add opening money or record a transaction.",
    amountSource: "Where this amount came from",
    eachAmountSource: "Each amount is linked to a recorded transaction.",
    selectLocation: "Choose a place to see the transactions behind its amount.",
    recordedTransaction: "Recorded transaction",
    peopleTitle: "Customers & Sarafs",
    peopleIntro:
      "Find a person and see clearly whether they owe you or you owe them.",
    searchPeople: "Search customers or Sarafs",
    searchPeoplePlaceholder: "Name or phone",
    viewStatement: "View statement",
    noPeopleMatch: "No person matches this search.",
    statement: "Statement",
    balancesStaySeparate:
      "Each currency stays separate so the amount remains clear.",
    closeStatement: "Close statement",
    documents: "Identity documents",
    documentType: "Document type",
    tazkira: "Tazkira",
    passport: "Passport",
    customerPhoto: "Customer photo",
    preview: "Preview",
    due: "Due",
    captureUpload: "Take photo or upload",
    noDocuments: "No identity document has been added for this person.",
    balanceDetails: "Balance details",
    noOutstanding: "This person has no unpaid balance.",
    statementHistory: "History",
    noStatementHistory: "No activity has been recorded for this person.",
    transactionHistory: "Transaction history",
    transactionIntro:
      "See what happened, when it happened, and whether it was completed or corrected.",
    noTransactions:
      "No transactions yet. Use New transaction to record the first one.",
    correction: "CORRECTION",
    correctTransaction: "Correct a transaction",
    originalReference: "Original reference",
    correctionReason: "Why does this need correction?",
    submitCorrection: "Send correction request",
    ratesTitle: "Shop rates",
    ratesIntro:
      "Current approved buy and sell rates, with past changes kept for reference.",
    rateHistory: "Rate history",
    shopDefault: "Shop default",
    branchRate: "Branch rate",
    effectiveFrom: "Used from",
    noRateHistory: "No approved rate has been added yet.",
    calculatorNote:
      "The calculator is only a preview. A transaction is saved only when you confirm it.",
    reportsTitle: "Reports",
    reportsIntro: "Prepare profit, money, transaction, and customer reports.",
    reportType: "Report type",
    reportDaily: "All activity",
    reportFx: "Currency trades",
    reportCash: "Cash movements",
    reportDebt: "Debts and payments",
    reportLoading: "Loading complete ledger records…",
    from: "From",
    to: "To",
    all: "All",
    printA4: "Print A4",
    print58: "Print 58mm",
    print80: "Print 80mm",
    shareWhatsApp: "Share on WhatsApp",
    reportsReady: "matching transactions are ready for export.",
    noReportRows: "No transactions match these filters.",
    debtsTitle: "Debts",
    debtsIntro:
      "Record who owes you and who you owe, in the original currency.",
    choosePerson: "Choose a customer or Saraf",
    postDebt: "Save debt",
    posting: "Saving…",
    noDebts: "No unpaid debts. Add one only when money is actually owed.",
    settleDebt: "Record debt payment",
    remaining: "Remaining",
    paymentAmount: "Payment amount",
    savePayment: "Save payment",
    settlementNote:
      "Payments reduce the remaining amount and stay visible in the history.",
    cashboxTitle: "Check cashbox",
    cashboxIntro:
      "Compare the cash you counted with the amount SARAFI expects.",
    expected: "Expected",
    counted: "Counted",
    difference: "Difference",
    loading: "Loading…",
    differenceReason: "Reason for the difference",
    reasonRequired: "Explain any shortage or extra cash",
    submitCashCount: "Send cash count for review",
    cashDifferenceNote:
      "Any shortage or extra cash stays visible until an authorized person reviews it.",
    hawalaTitle: "Hawala",
    hawalaIntro:
      "Record the receiver, destination, amount, fee, and reference.",
    fullBeneficiaryName: "Receiver’s full name",
    cityCountry: "City or country",
    uniqueReference: "Unique reference",
    noHawala: "No Hawala transfer has been recorded yet.",
    compliance: "Compliance review",
    recentActivity: "Recent activity",
    traceable: "Every money movement is recorded and can be reviewed.",
    tradeReference: "Transaction",
    viewTradeDetails: "View transaction details",
    detailsAfterSync:
      "Transaction details will be available after the latest data loads.",
    couldNotLoad: "We could not load this information. Please try again.",
    couldNotSave:
      "We could not save this action. Check the details and try again.",
    savedSuccessfully: "Saved successfully.",
    businessSetupRequired:
      "Finish setting up the shop before saving this action.",
    activeBranchRequired: "Choose an active branch before saving this action.",
    activeCashboxRequired:
      "Choose an active cashbox before saving this action.",
    connectionRequired: "Reconnect to the internet before saving this action.",
    amountGreaterZero: "Enter an amount greater than zero.",
    exportUnavailable: "This report cannot be exported right now.",
    exportReady: "The report is ready.",
    reversed: "Corrected",
    requestFailed: "We could not complete this request. Please try again.",
    authInvalidCredentials: "The email address or password is incorrect.",
    authEmailNotConfirmed: "Confirm your email address before signing in.",
    authTooManyAttempts: "Too many attempts. Wait a moment, then try again.",
    authRequestTimedOut: "The secure sign-in service took too long to respond. Please try again.",
    authServiceUnreachable: "We could not reach the secure sign-in service. Check your connection and try again.",
    authConfigurationError: "Secure sign-in is not configured correctly. Please contact your administrator.",
    afghanAfghani: "Afghan Afghani",
    device: "Device",
    approved: "Approved",
    rejected: "Not approved",
    documentSaved: "Identity document saved securely.",
    shareOpened: "WhatsApp is ready to share this report.",
    direction: "Who owes whom?",
    person: "Customer or Saraf",
    counterparty: "Customer or Saraf",
    choosePersonFirst: "Choose a customer or Saraf before saving this debt.",
    settling: "Saving…",
    outstanding: "Remaining amount",
    expectedVsCounted: "Expected and counted cash",
    countedAmount: "Counted amount",
    expectedAmount: "Expected amount",
    variance: "Difference",
    submitting: "Sending…",
    optionalSection: "OPTIONAL SERVICE",
    receiver: "Receiver",
    amountAfn: "Amount (AFN)",
    feeAfn: "Fee (AFN)",
    postingHawala: "Saving…",
    hawalaBaseAmount: "Amount value in AFN",
    hawalaFeeBaseAmount: "Fee value in AFN",
    hawalaCustomer: "Hawala customer",
    saveHawala: "Save Hawala",
    languageNameEnglish: "English",
    languageNameDari: "Dari",
    languageNamePashto: "Pashto",
    firstSetup: "FIRST SHOP SETUP",
    setupTitle: "Set up your Sarafi",
    setupIntro:
      "Start with the essential shop details. You can change advanced settings later.",
    businessNameQuestion: "What is your Sarafi called?",
    businessNamePlaceholder: "Sarwari Exchange",
    mainBranchName: "Main branch name",
    mainBranchPlaceholder: "Main branch",
    currenciesQuestion: "Which currencies do you use?",
    mainCashboxName: "Main cashbox name",
    mainCashboxPlaceholder: "Main Counter",
    startingCurrency: "Starting currency",
    selectedCurrencies: "Selected currencies",
    nextStep: "Next step",
    onboardingNext: "Add opening money, then record your first transaction",
    firstDayTitle: "Finish your first-day setup",
    firstDayIntro: "Four short steps make the shop ready for daily work.",
    creatingBusiness: "Creating shop…",
    createBusiness: "Create my Sarafi",
    switchingShop: "MOVING EXISTING DATA",
    importCenter: "Import center",
    importIntro:
      "Check an import before any customer, opening-money, or debt record is saved.",
    importType: "What are you importing?",
    counterparties: "Customers and Sarafs",
    openingBalances: "Opening money",
    downloadTemplate: "Download CSV template",
    chooseCsv: "Choose CSV file",
    previewComplete: "File check complete. No records were changed.",
    csvReadFailed:
      "This CSV file could not be read. Check the template and try again.",
    rowsChecked: "Rows checked",
    issues: "Issues",
    readyToImport: "Ready to import",
    yes: "Yes",
    no: "No",
    total: "Total",
    row: "Row",
    fixRequired: "Fix required",
    importReady:
      "The checked file is ready. Confirm only if these records are correct.",
    confirmImport: "Confirm import",
    importSaved: "records imported successfully.",
    reviewTransaction: "Review transaction",
    confirmTransaction: "Confirm and save",
    editTransaction: "Edit transaction",
    confirmationTitle: "Check before saving",
    confirmationIntro:
      "Confirm that the shop gives and receives these exact amounts.",
    pairRateUnavailable:
      "No approved rate is available for this currency pair. Ask an authorized person to add the rate before exchanging.",
    addDebt: "Add debt",
    postingPaused: "Financial saving is paused until the connection returns.",
    retry: "Try again",
    sourceCurrency: "Calculator source currency",
    targetCurrency: "Calculator target currency",
    moreBusiness: "Reports, rates & cashboxes",
    moreTeam: "Employees, approvals & devices",
    moreSettings: "Shop & security settings",
    moreAdvanced: "Import, Hawala & compliance",
  },
  "fa-AF": {
    sarafiTagline: "دفتر دیجیتلی برای صرافی‌ها",
    openingLabel: "صفحه آغاز صرافی",
    skipOpening: "رد کردن",
    owner: "مالک",
    cashier: "صندوق‌دار",
    manager: "مدیر",
    accountant: "محاسب",
    viewer: "بیننده",
    complianceOfficer: "مسئول بررسی",
    businessGroup: "صرافی",
    teamGroup: "کارمندان",
    settingsGroup: "تنظیمات",
    advancedGroup: "بخش پیشرفته",
    importData: "انتقال معلومات",
    connectionNotice: "معلومات صرافی شما وصل است",
    yourBusiness: "صرافی شما",
    assignedBranch: "شعبه تعیین‌شده",
    activeBranchSelected: "این شعبه فعال شما است.",
    signOut: "خروج",
    showAmounts: "نشان دادن مبالغ",
    hideAmounts: "پنهان کردن مبالغ",
    changeLanguage: "تغییر زبان",
    openHelp: "باز کردن راهنما",
    coreCashierActions: "کارهای روزمره صندوق‌دار",
    startTransaction: "ثبت یک کار جدید",
    chooseDailyAction:
      "کاری را که انجام شده انتخاب کنید؛ SARAFI مرحله‌به‌مرحله راهنمایی می‌کند.",
    readOnlyRoleNotice:
      "این دسترسی فقط برای دیدن است. برای ثبت یا تغییر پول از مالک اجازه بخواهید.",
    liveBuyRate: "نرخ فعلی خرید",
    liveSellRate: "نرخ فعلی فروش",
    liveRate: "نرخ فعلی",
    rateCalculator: "مبلغ برای محاسبه نرخ",
    businessDate: "تاریخ کاری",
    allTime: "همه زمان‌ها",
    status: "وضعیت",
    shopAction: "عملیات صرافی",
    income: "درآمد",
    ownerWithdrawal: "برداشت مالک",
    bankDeposit: "واریز به بانک",
    bankWithdrawal: "برداشت از بانک",
    rent: "کرایه",
    salary: "معاش",
    utilities: "آب و برق",
    internet: "انترنت",
    transport: "ترانسپورت",
    other: "سایر",
    reasonReference: "دلیل یا شماره مرجع",
    shopCheck: "سرافی پیش از ثبت، اجازه، صرافی و جزئیات پول را بررسی می‌کند.",
    helpIntro:
      "برای کارهای روزمره از فهرست اصلی استفاده کنید. عملیات پولی تنها پس از ورود و بررسی سرافی ثبت می‌شود.",
    openingBalance: "پول آغاز کار",
    recordOpeningMoney: "ثبت پول آغاز کار",
    startingAmount: "مبلغ همین اسعار",
    afnValue: "ارزش به افغانی",
    saveOpeningMoney: "ثبت پول آغاز کار",
    openingMoneyNote:
      "این بخش تنها برای پولی است که صرافی پیش از آغاز کار با سرافی داشت. این پول مفاد نیست.",
    backHome: "بازگشت به خانه",
    workspaceSection: "این بخش از فهرست اصلی در دسترس است.",
    transactionsDescription: "فعالیت ثبت‌شده و معاملات گذشته صرافی را ببینید.",
    moneyDescription: "مقدار پول هر اسعار و محل نگهداری آن را ببینید.",
    peopleDescription:
      "مشتریان و صرافان را پیدا کنید و ببینید چه کسی به چه کسی بدهکار است.",
    debtsDescription:
      "پولی را که مردم به شما بدهکار اند یا شما به آنان بدهکار هستید ثبت و بررسی کنید.",
    ratesDescription: "نرخ‌های مجاز خرید و فروش صرافی را ببینید.",
    reportsDescription: "گزارش تجارت، مفاد و معاملات را آماده کنید.",
    teamDescription: "کارمندان، دستگاه‌ها و تأییدها را مدیریت کنید.",
    settingsDescription: "صرافی، زبان‌ها، اسعار و امنیت را تنظیم کنید.",
    teamAccess: "دسترسی کارمندان",
    teamIntro:
      "ببینید چه کسی به صرافی دسترسی دارد، کدام دستگاه فعال است و چه چیزی تأیید می‌خواهد.",
    previewOwnerName: "مالک صرافی",
    previewCashierName: "صندوق‌دار اصلی",
    previewCashboxName: "صندوق اصلی",
    previewSafeName: "خزانه اصلی",
    previewBankName: "حساب بانکی اصلی",
    previewBankReference: "چهار رقم اخیر ۱۲۳۴",
    moneyAccountsTitle: "صندوق‌ها و حساب‌های پولی",
    moneyAccountsIntro: "هر محل واقعی نگهداری پول را یک‌بار بسازید. هنگام معامله فقط انتخاب کنید پول از کجا می‌آید و به کجا می‌رود.",
    addMoneyAccount: "افزودن حساب پولی",
    accountName: "نام حساب",
    accountNamePlaceholder: "مثلاً خزانه اصلی یا عزیزی بانک",
    accountType: "نوع حساب",
    accountReference: "نشانی کوتاه (اختیاری)",
    accountReferencePlaceholder: "مثلاً چهار رقم اخیر ۱۲۳۴",
    accountType_cashbox: "صندوق",
    accountType_safe: "خزانه",
    accountType_bank: "حساب بانکی",
    accountType_mobile_money: "کیف پول موبایلی",
    accountType_partner: "حساب همکار",
    accountType_other: "حساب دیگر",
    saveMoneyAccount: "ذخیره حساب",
    accountCreated: "حساب پولی افزوده شد.",
    accountCreateFailed: "حساب پولی افزوده نشد. نام را بررسی کنید و دوباره کوشش کنید.",
    noMoneyInAccount: "هنوز پولی در این حساب ثبت نشده است",
    noMoneyAccounts: "هنوز حساب پولی آماده نیست. مالک باید پیش از ثبت معاملات روزانه یک حساب بسازد.",
    ownerOnlyAccounts: "فقط مالک می‌تواند حساب پولی را اضافه یا تغییر دهد. کارمندان تنها از حساب‌های تعیین‌شده استفاده می‌کنند.",
    shopCurrenciesTitle: "اسعار مورد استفاده صرافی",
    shopCurrenciesIntro: "فهرست جهانی در دسترس است. فقط اسعار خرید، فروش، دریافت یا پرداخت صرافی را فعال کنید.",
    enabledCurrencies: "اسعار آماده برای استفاده",
    manageCurrencies: "مدیریت اسعار",
    manageCurrenciesIntro:
      "تنظیمات مالک: اسعار مورد نیاز صرافی را در فهرست جهانی جستجو و فعال یا غیرفعال کنید.",
    baseCurrency: "اسعار اصلی",
    searchCurrency: "پیدا کردن اسعار",
    searchCurrencyPlaceholder: "کُد یا نام؛ مثلاً CNY",
    usedInShop: "مورد استفاده صرافی",
    currencyOwnerHelp: "این فهرست در اختیار مالک است. فعال‌سازی اسعار آن را در فورم‌های روزانه می‌آورد؛ معامله اسعار هنوز به نرخ تأییدشده نیاز دارد.",
    ownerOnlyCurrencies: "فقط مالک می‌تواند فهرست اسعار صرافی را تغییر دهد.",
    currencyUpdated: "فهرست اسعار صرافی به‌روز شد.",
    currencyUpdateFailed: "این تغییر ذخیره نشد. اسعار دارای موجودی را نمی‌توان غیرفعال کرد.",
    addWorldCurrency: "افزودن اسعار دیگر جهان",
    chooseWorldCurrency: "از فهرست جهانی اسعار انتخاب کنید",
    sourceAccount: "پول از این حساب می‌آید",
    destinationAccount: "پول به این حساب می‌رود",
    chooseMoneyAccount: "یک حساب پولی را انتخاب کنید",
    chooseSourceAccount: "حساب مبدأ را انتخاب کنید",
    chooseDestinationAccount: "حساب مقصد را انتخاب کنید",
    accountsMustDiffer: "برای انتقال، دو حساب متفاوت را انتخاب کنید.",
    valueInBaseCurrency: "ارزش به افغانی",
    baseValueHelp: "ارزش افغانی مورد استفاده در دفتر را وارد کنید. مبالغ اسعار مختلف بدون ارزش‌گذاری باهم جمع نمی‌شوند.",
    customerOutside: "مشتری یا شخص بیرون از صرافی",
    outsideAccount: "حساب بیرون از صرافی",
    openingFundsSource: "سرمایه آغاز کار",
    incomeSource: "منبع عاید",
    expenseDestination: "مصرف",
    ownerPersonal: "پول شخصی مالک",
    activeCashboxAccount: "صندوق فعال",
    tradeMoneyFlow: "حساب‌های مورد استفاده در این معامله",
    tradeHasTwoMoneySides: "اسعار خارجی و افغانی در دو جهت مخالف حرکت می‌کنند. هر دو طرف در صندوق انتخاب‌شده ثبت می‌شود.",
    noCurrentRate: "نرخ فعلی موجود نیست",
    setShopRate: "تعیین نرخ تأییدشده صرافی",
    setShopRateIntro: "مقدار افغانی برابر با یک واحد اسعار انتخاب‌شده را وارد کنید. نرخ قبلی در تاریخچه می‌ماند.",
    foreignCurrency: "اسعار خارجی",
    ratePerUnitPlaceholder: "افغانی برای یک واحد",
    saveShopRate: "ذخیره نرخ تأییدشده",
    ownerOnlyRates: "فقط مالک می‌تواند نرخ تأییدشده صرافی را تعیین کند.",
    rateSaved: "نرخ تأییدشده ذخیره شد.",
    rateSaveFailed: "نرخ ذخیره نشد. هر دو اسعار را فعال و ارقام را بررسی کنید.",
    addEmployee: "افزودن کارمند",
    addEmployeeIntro: "کارمند را دعوت کنید و دقیقاً مشخص سازید در کدام شعبه و صندوق کار کند.",
    fullName: "نام کامل",
    workEmail: "ایمیل کاری",
    employeeRole: "وظیفه",
    branchAccess: "شعبه‌های مجاز",
    cashboxAccess: "صندوق‌های مجاز",
    businessWideAccess: "این وظیفه به تمام صرافی دسترسی دارد.",
    cashierScopeRequired: "برای صندوق‌دار حداقل یک شعبه و یک صندوق را انتخاب کنید.",
    sendInvite: "ساختن دعوت",
    sendingInvite: "دعوت ساخته می‌شود…",
    pendingInvitations: "دعوت‌های در انتظار",
    noPendingInvites: "دعوتی در انتظار نیست.",
    inviteCreated: "دعوت آماده شد",
    inviteLinkInstructions: "این لینک خصوصی را کاپی کرده و برای کارمند بفرستید. لینک پس از ۷۲ ساعت منقضی می‌شود.",
    copyInviteLink: "کاپی لینک دعوت",
    linkCopied: "لینک دعوت کاپی شد.",
    emailInvite: "فرستادن با ایمیل",
    expires: "اعتبار تا",
    cancelInvite: "لغو دعوت",
    editAccess: "تغییر دسترسی",
    saveAccess: "ثبت دسترسی",
    suspendAccess: "توقف دسترسی",
    reactivateAccess: "فعال‌سازی دوباره",
    accessChangeReason: "دلیل این تغییر",
    cancelAction: "انصراف",
    assignedTo: "محل وظیفه",
    noSpecificScope: "دسترسی به تمام صرافی",
    memberSince: "عضو از",
    invited: "دعوت‌شده",
    secureTeamAction: "تأیید عملیات امن",
    secureTeamIntro: "تغییر دسترسی کارمندان به ورود دومرحله‌ای نیاز دارد تا در صورت سرقت رمز، صرافی محفوظ بماند.",
    setupAuthenticator: "تنظیم برنامهٔ رمزساز",
    authenticatorInstructions: "این کود را با برنامهٔ رمزساز اسکن کنید، سپس کود شش‌رقمی را وارد نمایید.",
    authenticatorSecret: "کود تنظیم دستی",
    verificationCode: "کود شش‌رقمی",
    verifySecurity: "تأیید و ادامه",
    verifyingSecurity: "در حال تأیید…",
    securityVerified: "عملیات امن تأیید شد.",
    mfaSetupFailed: "تنظیم برنامهٔ رمزساز آغاز نشد. دوباره کوشش کنید.",
    mfaVerificationFailed: "این کود پذیرفته نشد. کود را بررسی کرده و دوباره کوشش کنید.",
    teamLoadFailed: "معلومات کارمندان بارگذاری نشد.",
    teamSaveFailed: "تغییر کارمند ثبت نشد. معلومات را بررسی کرده و دوباره کوشش کنید.",
    joinTeam: "پیوستن به تیم صرافی",
    joinTeamSubtitle: "با همان ایمیلی وارد شوید یا حساب بسازید که دعوت به آن فرستاده شده است.",
    createAndJoin: "ساخت حساب و پیوستن",
    invitationAccepted: "دعوت پذیرفته شد. محیط کاری تعیین‌شده آماده است.",
    invitationInvalid: "این لینک دعوت نادرست است یا دیگر اعتبار ندارد.",
    invitationExpired: "مدت این دعوت تمام شده است. از مالک دعوت تازه بخواهید.",
    invitationWrongAccount: "از همان ایمیلی استفاده کنید که مالک دعوت کرده است.",
    signOutDifferentAccount: "خروج و استفاده از حساب دیگر",
    active: "فعال",
    suspended: "متوقف",
    accessOn: "دسترسی دارد",
    accessOff: "دسترسی ندارد",
    extraSecurityRequired: "امنیت اضافی ورود لازم است",
    normalSecurity: "امنیت عادی ورود",
    registeredDevices: "دستگاه‌های ثبت‌شده",
    lastSeen: "آخرین فعالیت",
    revoked: "لغوشده",
    approvalInbox: "درخواست‌های تأیید",
    approvalRequest: "درخواست تأیید",
    requested: "درخواست‌شده",
    review: "بررسی",
    noTeam: "هنوز کارمندی اضافه نشده است.",
    noDevices: "هنوز دستگاهی ثبت نشده است.",
    deviceLinkFailed: "این مرورگر وصل نشد. پیش از ذخیره معامله دوباره کوشش کنید.",
    previewCustomer: "مشتری حضوری",
    platformAdministrator: "مدیر عمومی سیستم",
    platformAdministratorSignIn: "با حساب جداگانه مدیر وارد شوید. مالک و کارمندان صرافی از صفحه اصلی وارد می‌شوند.",
    planPayment: "بسته و پرداخت",
    addCustomer: "افزودن مشتری",
    customerName: "نام مشتری یا صراف",
    customerType: "نوع",
    customerTypeCustomer: "مشتری",
    customerTypeSaraf: "صراف",
    customerTypeHawala: "همکار حواله",
    customerTypeSupplier: "فروشنده",
    customerTypeEmployee: "کارمند",
    phoneOptional: "شماره تماس (اختیاری)",
    saveCustomer: "ذخیره مشتری",
    customerCreated: "مشتری ذخیره شد و آماده استفاده است.",
    customerCreateFailed: "مشتری ذخیره نشد. نام را بررسی و دوباره کوشش کنید.",
    deviceAwaitingOwner: "این مرورگر وصل شده و منتظر تأیید مالک است. اکنون می‌توانید معلومات را ببینید؛ ذخیره حرکت پول پس از تأیید باز می‌شود.",
    deviceTrusted: "تأییدشده",
    deviceWaiting: "منتظر تأیید",
    deviceControlIntro: "مرورگر جدید کارمند را پیش از ذخیره حرکت پول تأیید کنید. مرورگر گم‌شده یا مشترک را فوری لغو کنید.",
    deviceReasonRequired: "برای تغییر دستگاه یک دلیل کوتاه بنویسید.",
    deviceReasonPlaceholder: "نمونه: کمپیوتر صندوق بررسی شد",
    approveDevice: "تأیید دستگاه",
    revokeDevice: "لغو دستگاه",
    deviceApproved: "دستگاه تأیید و آماده شد.",
    deviceRevoked: "دسترسی دستگاه لغو شد.",
    moneyPlacesCount: "جای پول",
    roleHomeTitle_owner: "مرکز کنترول مالک",
    roleHomeDescription_owner: "تمام صرافی، کارمندان، دستگاه‌ها، پرداخت و کنترول‌ها را در یک جا ببینید.",
    roleHomeTitle_manager: "کارهای روزانه",
    roleHomeDescription_manager: "شعبه‌ها و کار روزانه را پیش ببرید و کارهای عملیاتی را بررسی کنید؛ تنظیمات مخصوص مالک جدا است.",
    roleHomeTitle_accountant: "حساب‌ها و گزارش‌ها",
    roleHomeDescription_accountant: "مانده‌ها، گزارش‌ها و بررسی صندوق را ببینید. این نقش حرکت پول را ذخیره نمی‌کند.",
    roleHomeTitle_cashier: "صندوق امروز من",
    roleHomeDescription_cashier: "خرید، فروش، دریافت، پرداخت و بررسی همان صندوقی را انجام دهید که به شما سپرده شده است.",
    roleHomeTitle_compliance_officer: "بررسی مقررات",
    roleHomeDescription_compliance_officer: "بررسی مشتری، هشدارها، دوسیه‌ها و اسناد لازم را بدون ثبت معامله انجام دهید.",
    roleHomeTitle_viewer: "مشاهده بدون تغییر",
    roleHomeDescription_viewer: "مانده‌ها، گزارش‌ها و تاریخچه معاملات تأییدشده را بدون تغییر ببینید.",
    customerLabel: "مشتری",
    employeeLabel: "کارمند",
    teamMember: "عضو تیم",
    weGaveLabel: "ما دادیم",
    weReceivedLabel: "ما گرفتیم",
    confirmPassword: "تکرار رمز عبور",
    fullNameRequired: "نام کامل خود را بنویسید.",
    passwordsDoNotMatch: "دو رمز عبور یکسان نیست.",
    ownerSignupOnly: "ساختن صرافی جدید",
    workerUsesInvite: "تنها مالک از اینجا صرافی جدید می‌سازد. کارمند از لینک دعوت مالک حساب خود را می‌سازد یا وارد می‌شود.",
    everyoneSignsInHere: "مالک، مدیر، صندوق‌دار، حسابدار، مسئول مقررات و ناظر",
    signInRoleAutomatic: "همه از همین‌جا وارد می‌شوند. صرافی تنها وظیفه، شعبه و صندوق تعیین‌شده برای آن حساب را باز می‌کند.",
    cashierCloseShortcut: "بستن صندوق من",
    noApprovals: "درخواست تأییدی وجود ندارد.",
    selfApprovalRule: "هیچ‌کس نمی‌تواند درخواست خودش را تأیید کند.",
    accessRuleNote:
      "اجازه، شعبه، صندوق، دستگاه و تأیید هنگام ثبت هر عملیات خودکار بررسی می‌شود.",
    whereIsMoney: "پول من کجا است؟",
    moneyIntro:
      "پول را بر اساس اسعار و محل ببینید؛ هر مبلغ به معامله ثبت‌شده مربوط است.",
    allCurrencies: "همه اسعار",
    currencyFirst: "بر اساس اسعار",
    locationFirst: "بر اساس محل",
    printSnapshot: "چاپ این صفحه",
    theyOweUs: "آنها به ما بدهکار اند",
    weOweThem: "ما به آنها بدهکار هستیم",
    postedRecords: "معاملات ثبت‌شده",
    loadingMoney: "پول شما در حال بارگذاری است…",
    totalCurrency: "مجموع همین اسعار",
    moneyAtPlace: "پول در این محل · برای جزئیات باز کنید",
    noMoney: "هنوز پولی ثبت نشده است. پول آغاز کار یا یک معامله را ثبت کنید.",
    amountSource: "این مبلغ از کجا آمده است",
    eachAmountSource: "هر مبلغ به یک معامله ثبت‌شده مربوط است.",
    selectLocation:
      "یک محل را انتخاب کنید تا معاملات مربوط به مبلغ آن را ببینید.",
    recordedTransaction: "معامله ثبت‌شده",
    peopleTitle: "مشتریان و صرافان",
    peopleIntro:
      "یک شخص را پیدا کنید و روشن ببینید او به شما بدهکار است یا شما به او.",
    searchPeople: "جستجوی مشتری یا صراف",
    searchPeoplePlaceholder: "نام یا شماره تماس",
    viewStatement: "دیدن صورت‌حساب",
    noPeopleMatch: "شخصی با این جستجو پیدا نشد.",
    statement: "صورت‌حساب",
    balancesStaySeparate: "هر اسعار جدا نگهداری می‌شود تا مبلغ روشن بماند.",
    closeStatement: "بستن صورت‌حساب",
    documents: "اسناد هویتی",
    documentType: "نوع سند",
    tazkira: "تذکره",
    passport: "پاسپورت",
    customerPhoto: "عکس مشتری",
    preview: "دیدن",
    due: "سررسید",
    captureUpload: "عکس بگیرید یا بارگذاری کنید",
    noDocuments: "برای این شخص هنوز سند هویتی اضافه نشده است.",
    balanceDetails: "جزئیات طلب و بدهی",
    noOutstanding: "این شخص مبلغ پرداخت‌نشده ندارد.",
    statementHistory: "تاریخچه",
    noStatementHistory: "برای این شخص هنوز فعالیتی ثبت نشده است.",
    transactionHistory: "تاریخچه معاملات",
    transactionIntro: "ببینید چه کاری، چه زمانی و با چه وضعیتی انجام شده است.",
    noTransactions: "هنوز معامله‌ای ثبت نشده است. از «معامله جدید» آغاز کنید.",
    correction: "اصلاح",
    correctTransaction: "اصلاح یک معامله",
    originalReference: "شماره معامله اصلی",
    correctionReason: "چرا این معامله باید اصلاح شود؟",
    submitCorrection: "فرستادن درخواست اصلاح",
    ratesTitle: "نرخ‌های صرافی",
    ratesIntro: "نرخ فعلی مجاز خرید و فروش، همراه با تغییرات گذشته.",
    rateHistory: "تاریخچه نرخ",
    shopDefault: "نرخ عمومی صرافی",
    branchRate: "نرخ شعبه",
    effectiveFrom: "قابل استفاده از",
    noRateHistory: "هنوز نرخ مجازی اضافه نشده است.",
    calculatorNote:
      "محاسبه‌گر تنها پیش‌نمایش است. معامله فقط پس از تأیید شما ثبت می‌شود.",
    reportsTitle: "گزارش‌ها",
    reportsIntro: "گزارش مفاد، پول، معاملات و مشتریان را آماده کنید.",
    reportType: "نوع گزارش",
    reportDaily: "تمام عملیات",
    reportFx: "معاملات اسعار",
    reportCash: "حرکت‌های پول",
    reportDebt: "طلب، بدهی و پرداخت",
    reportLoading: "تمام ثبت‌های دفتر در حال بارگذاری است…",
    from: "از",
    to: "تا",
    all: "همه",
    printA4: "چاپ A4",
    print58: "چاپ ۵۸ میلی‌متر",
    print80: "چاپ ۸۰ میلی‌متر",
    shareWhatsApp: "فرستادن در واتس‌اپ",
    reportsReady: "معامله برای صدور آماده است.",
    noReportRows: "معامله‌ای با این فلترها پیدا نشد.",
    debtsTitle: "طلب و بدهی",
    debtsIntro:
      "ثبت کنید چه کسی به شما بدهکار است و شما به چه کسی بدهکار هستید.",
    choosePerson: "یک مشتری یا صراف را انتخاب کنید",
    postDebt: "ثبت قرض",
    posting: "در حال ثبت…",
    noDebts:
      "قرض پرداخت‌نشده وجود ندارد. تنها زمانی اضافه کنید که واقعاً پولی بدهکار باشد.",
    settleDebt: "ثبت پرداخت قرض",
    remaining: "باقی‌مانده",
    paymentAmount: "مبلغ پرداخت",
    savePayment: "ثبت پرداخت",
    settlementNote:
      "پرداخت، مبلغ باقی‌مانده را کم می‌کند و در تاریخچه باقی می‌ماند.",
    cashboxTitle: "بررسی صندوق",
    cashboxIntro: "پول شمارش‌شده را با مبلغ مورد انتظار سرافی مقایسه کنید.",
    expected: "مورد انتظار",
    counted: "شمارش‌شده",
    difference: "تفاوت",
    loading: "در حال بارگذاری…",
    differenceReason: "دلیل تفاوت",
    reasonRequired: "دلیل کمبود یا پول اضافی را بنویسید",
    submitCashCount: "فرستادن شمارش صندوق برای بررسی",
    cashDifferenceNote:
      "کمبود یا پول اضافی تا بررسی شخص مجاز روشن باقی می‌ماند.",
    hawalaTitle: "حواله",
    hawalaIntro: "گیرنده، مقصد، مبلغ، کمیشن و شماره مرجع را ثبت کنید.",
    fullBeneficiaryName: "نام کامل گیرنده",
    cityCountry: "شهر یا کشور",
    uniqueReference: "شماره مرجع یکتا",
    noHawala: "هنوز حواله‌ای ثبت نشده است.",
    compliance: "بررسی اصول کاری",
    recentActivity: "فعالیت اخیر",
    traceable: "هر حرکت پول ثبت می‌شود و قابل بررسی است.",
    tradeReference: "معامله",
    viewTradeDetails: "دیدن جزئیات معامله",
    detailsAfterSync:
      "جزئیات معامله پس از بارگذاری تازه‌ترین معلومات در دسترس می‌شود.",
    couldNotLoad: "این معلومات بارگذاری نشد. لطفاً دوباره کوشش کنید.",
    couldNotSave: "این عملیات ثبت نشد. جزئیات را بررسی و دوباره کوشش کنید.",
    savedSuccessfully: "با موفقیت ثبت شد.",
    businessSetupRequired: "پیش از ثبت این عملیات، تنظیم صرافی را تکمیل کنید.",
    activeBranchRequired: "پیش از ثبت این عملیات یک شعبه فعال انتخاب کنید.",
    activeCashboxRequired: "پیش از ثبت این عملیات یک صندوق فعال انتخاب کنید.",
    connectionRequired: "پیش از ثبت این عملیات دوباره به انترنت وصل شوید.",
    amountGreaterZero: "مبلغی بیشتر از صفر وارد کنید.",
    exportUnavailable: "در حال حاضر این گزارش صادر نمی‌شود.",
    exportReady: "گزارش آماده است.",
    reversed: "اصلاح‌شده",
    requestFailed: "این درخواست انجام نشد. لطفاً دوباره کوشش کنید.",
    authInvalidCredentials: "آدرس ایمیل یا رمز عبور نادرست است.",
    authEmailNotConfirmed: "پیش از ورود، آدرس ایمیل خود را تأیید کنید.",
    authTooManyAttempts: "کوشش‌های بسیار انجام شده است. کمی صبر کنید و دوباره کوشش کنید.",
    authRequestTimedOut: "پاسخ خدمات امن ورود بیش از حد طول کشید. لطفاً دوباره کوشش کنید.",
    authServiceUnreachable: "ارتباط با خدمات امن ورود برقرار نشد. اتصال انترنت را بررسی و دوباره کوشش کنید.",
    authConfigurationError: "خدمات امن ورود درست تنظیم نشده است. با مسئول سیستم تماس بگیرید.",
    afghanAfghani: "افغانی افغانستان",
    device: "دستگاه",
    approved: "تأییدشده",
    rejected: "تأییدنشده",
    documentSaved: "سند هویتی به‌گونه امن ثبت شد.",
    shareOpened: "واتس‌اپ برای فرستادن این گزارش آماده است.",
    direction: "چه کسی به چه کسی بدهکار است؟",
    person: "مشتری یا صراف",
    counterparty: "مشتری یا صراف",
    choosePersonFirst: "پیش از ثبت قرض یک مشتری یا صراف را انتخاب کنید.",
    settling: "در حال ثبت…",
    outstanding: "مبلغ باقی‌مانده",
    expectedVsCounted: "پول مورد انتظار و شمارش‌شده",
    countedAmount: "مبلغ شمارش‌شده",
    expectedAmount: "مبلغ مورد انتظار",
    variance: "تفاوت",
    submitting: "در حال فرستادن…",
    optionalSection: "خدمت اختیاری",
    receiver: "گیرنده",
    amountAfn: "مبلغ (افغانی)",
    feeAfn: "کمیشن (افغانی)",
    postingHawala: "در حال ثبت…",
    hawalaBaseAmount: "ارزش مبلغ به افغانی",
    hawalaFeeBaseAmount: "ارزش کارمزد به افغانی",
    hawalaCustomer: "مشتری حواله",
    saveHawala: "ثبت حواله",
    languageNameEnglish: "انگلیسی",
    languageNameDari: "دری",
    languageNamePashto: "پښتو",
    firstSetup: "تنظیم نخست صرافی",
    setupTitle: "صرافی خود را تنظیم کنید",
    setupIntro:
      "از معلومات ضروری صرافی آغاز کنید. تنظیمات پیشرفته را بعداً تغییر داده می‌توانید.",
    businessNameQuestion: "نام صرافی شما چیست؟",
    businessNamePlaceholder: "صرافی سروری",
    mainBranchName: "نام شعبه اصلی",
    mainBranchPlaceholder: "شعبه مرکزی",
    currenciesQuestion: "از کدام اسعار استفاده می‌کنید؟",
    mainCashboxName: "نام صندوق اصلی",
    mainCashboxPlaceholder: "صندوق اصلی",
    startingCurrency: "اسعار اصلی",
    selectedCurrencies: "اسعار انتخاب‌شده",
    nextStep: "گام بعدی",
    onboardingNext: "پول آغاز کار را اضافه و سپس نخستین معامله را ثبت کنید",
    firstDayTitle: "تنظیم روز نخست را تکمیل کنید",
    firstDayIntro: "چهار گام کوتاه صرافی را برای کار روزانه آماده می‌کند.",
    creatingBusiness: "صرافی در حال ساخت است…",
    createBusiness: "ساختن صرافی من",
    switchingShop: "انتقال معلومات قبلی",
    importCenter: "مرکز انتقال معلومات",
    importIntro:
      "پیش از ثبت مشتریان، پول آغاز کار یا قرض‌ها، فایل را بررسی کنید.",
    importType: "چه معلوماتی را انتقال می‌دهید؟",
    counterparties: "مشتریان و صرافان",
    openingBalances: "پول آغاز کار",
    downloadTemplate: "دانلود نمونه CSV",
    chooseCsv: "انتخاب فایل CSV",
    previewComplete: "بررسی فایل تمام شد. هیچ معلوماتی تغییر نکرد.",
    csvReadFailed:
      "این فایل CSV خوانده نشد. نمونه را بررسی و دوباره کوشش کنید.",
    rowsChecked: "ردیف‌های بررسی‌شده",
    issues: "مشکلات",
    readyToImport: "آماده انتقال",
    yes: "بلی",
    no: "نخیر",
    total: "مجموع",
    row: "ردیف",
    fixRequired: "اصلاح لازم است",
    importReady:
      "فایل بررسی‌شده آماده است. تنها در صورت درستی معلومات تأیید کنید.",
    confirmImport: "تأیید انتقال",
    importSaved: "مورد با موفقیت انتقال شد.",
    reviewTransaction: "بررسی معامله",
    confirmTransaction: "تأیید و ثبت",
    editTransaction: "اصلاح معامله",
    confirmationTitle: "پیش از ثبت بررسی کنید",
    confirmationIntro:
      "تأیید کنید که صرافی دقیقاً همین مبالغ را می‌دهد و دریافت می‌کند.",
    pairRateUnavailable:
      "برای این جفت اسعار نرخ تأییدشده موجود نیست. پیش از تبادله از مسئول اجازه‌دار بخواهید نرخ را ثبت کند.",
    addDebt: "ثبت قرض",
    postingPaused: "ثبت عملیات مالی تا برگشت انترنت متوقف است.",
    retry: "کوشش دوباره",
    sourceCurrency: "اسعار مبدأ محاسبه‌گر",
    targetCurrency: "اسعار مقصد محاسبه‌گر",
    moreBusiness: "گزارش‌ها، نرخ‌ها و صندوق‌ها",
    moreTeam: "کارمندان، تأییدها و دستگاه‌ها",
    moreSettings: "تنظیمات صرافی و امنیت",
    moreAdvanced: "انتقال معلومات، حواله و بررسی",
  },
  "ps-AF": {
    sarafiTagline: "د صرافیو لپاره ډیجیټلي دفتر",
    openingLabel: "د صرافي د پیل پرده",
    skipOpening: "تېرول",
    owner: "مالک",
    cashier: "صندوق‌دار",
    manager: "مدیر",
    accountant: "محاسب",
    viewer: "کتونکی",
    complianceOfficer: "د څارنې مسئول",
    businessGroup: "صرافي",
    teamGroup: "کارکوونکي",
    settingsGroup: "امستنې",
    advancedGroup: "پرمختللې برخه",
    importData: "معلومات لېږدول",
    connectionNotice: "ستاسو د صرافۍ معلومات نښتي دي",
    yourBusiness: "ستاسو صرافي",
    assignedBranch: "ټاکل شوې څانګه",
    activeBranchSelected: "دا ستاسو فعاله څانګه ده.",
    signOut: "وتل",
    showAmounts: "مبلغونه ښودل",
    hideAmounts: "مبلغونه پټول",
    changeLanguage: "ژبه بدلول",
    openHelp: "لارښود پرانیستل",
    coreCashierActions: "د صندوق‌دار ورځني کارونه",
    startTransaction: "نوی کار ثبت کړئ",
    chooseDailyAction:
      "هغه کار وټاکئ چې شوی دی؛ SARAFI به مو پاتې پړاوونو کې لارښوونه وکړي.",
    readOnlyRoleNotice:
      "دا واک یوازې د کتلو لپاره دی. د پیسو د ثبت یا بدلون لپاره له مالک څخه اجازه وغواړئ.",
    liveBuyRate: "د پېرود اوسنی نرخ",
    liveSellRate: "د پلور اوسنی نرخ",
    liveRate: "اوسنی نرخ",
    rateCalculator: "د نرخ د محاسبې مبلغ",
    businessDate: "کاري نېټه",
    allTime: "ټول وخت",
    status: "حالت",
    shopAction: "د صرافۍ کړنه",
    income: "عاید",
    ownerWithdrawal: "د مالک ایستل",
    bankDeposit: "بانک ته جمع کول",
    bankWithdrawal: "له بانک څخه ایستل",
    rent: "کرایه",
    salary: "معاش",
    utilities: "اوبه او برېښنا",
    internet: "انټرنېټ",
    transport: "ترانسپورټ",
    other: "نور",
    reasonReference: "دلیل یا د حوالې شمېره",
    shopCheck: "صرافي له ثبتولو مخکې اجازه، کاروبار او د پیسو معلومات ګوري.",
    helpIntro:
      "د ورځنیو کارونو لپاره اصلي لېست وکاروئ. مالي کړنه یوازې له ننوتلو او د صرافي له تایید وروسته ثبتېږي.",
    openingBalance: "پیل پیسې",
    recordOpeningMoney: "پیل پیسې ثبتول",
    startingAmount: "د همدې اسعارو مبلغ",
    afnValue: "په افغانۍ ارزښت",
    saveOpeningMoney: "پیل پیسې ثبتول",
    openingMoneyNote:
      "دا برخه یوازې د هغو پیسو لپاره ده چې صرافۍ د سرافي له کارولو مخکې لرلې. دا پیسې ګټه نه ده.",
    backHome: "کور ته ستنېدل",
    workspaceSection: "دا برخه له اصلي لېست څخه موندل کېږي.",
    transactionsDescription: "د صرافۍ ثبت شوی فعالیت او پخوانۍ معاملې وګورئ.",
    moneyDescription: "په هر اسعار کې د خپلو پیسو اندازه او ځای وګورئ.",
    peopleDescription:
      "پېرودونکي او صرافان ومومئ او وګورئ چې څوک د چا پوروړی دی.",
    debtsDescription:
      "هغه پیسې ثبت او وګورئ چې خلک یې تاسو ته یا تاسو یې هغوی ته پوروړي یاست.",
    ratesDescription: "د صرافۍ مجاز د پېرود او پلور نرخونه وګورئ.",
    reportsDescription: "د کاروبار، ګټې او معاملو راپورونه چمتو کړئ.",
    teamDescription: "کارکوونکي، وسایل او تاییدونه اداره کړئ.",
    settingsDescription: "صرافي، ژبې، اسعار او امنیت تنظیم کړئ.",
    teamAccess: "د کارکوونکو لاسرسی",
    teamIntro:
      "وګورئ څوک صرافۍ ته لاسرسی لري، کوم وسایل فعال دي او څه تایید غواړي.",
    previewOwnerName: "د صرافۍ مالک",
    previewCashierName: "اصلي صندوق‌دار",
    previewCashboxName: "اصلي صندوق",
    previewSafeName: "اصلي خزانه",
    previewBankName: "اصلي بانکي حساب",
    previewBankReference: "وروستي شمېرې ۱۲۳۴",
    moneyAccountsTitle: "د پیسو صندوقونه او حسابونه",
    moneyAccountsIntro: "د پیسو د ساتلو هر رښتینی ځای یو ځل جوړ کړئ. د معاملې پر مهال یوازې وټاکئ چې پیسې له کوم حسابه راځي او کوم حساب ته ځي.",
    addMoneyAccount: "د پیسو حساب زیاتول",
    accountName: "د حساب نوم",
    accountNamePlaceholder: "لکه: اصلي خزانه یا عزیزي بانک",
    accountType: "د حساب ډول",
    accountReference: "لنډه نښه (اختیاري)",
    accountReferencePlaceholder: "لکه: وروستي شمېرې ۱۲۳۴",
    accountType_cashbox: "صندوق",
    accountType_safe: "خزانه",
    accountType_bank: "بانکي حساب",
    accountType_mobile_money: "موبایلي بټوه",
    accountType_partner: "د شریک حساب",
    accountType_other: "بل حساب",
    saveMoneyAccount: "حساب خوندي کول",
    accountCreated: "د پیسو حساب زیات شو.",
    accountCreateFailed: "د پیسو حساب زیات نه شو. نوم وګورئ او بیا هڅه وکړئ.",
    noMoneyInAccount: "تر اوسه دلته پیسې نه دي ثبت شوې",
    noMoneyAccounts: "د پیسو حساب لا چمتو نه دی. مالک باید د ورځنیو معاملو تر ثبت مخکې یو حساب جوړ کړي.",
    ownerOnlyAccounts: "یوازې مالک د پیسو حساب زیاتولی یا بدلولی شي. کارکوونکي یوازې ټاکل شوي حسابونه کارولی شي.",
    shopCurrenciesTitle: "د صرافۍ کارېدونکي اسعار",
    shopCurrenciesIntro: "نړیوال لېست شته. یوازې هغه اسعار فعال کړئ چې صرافي یې اخلي، پلوري، ترلاسه کوي یا ورکوي.",
    enabledCurrencies: "د کار لپاره چمتو اسعار",
    manageCurrencies: "اسعار اداره کړئ",
    manageCurrenciesIntro:
      "د مالک امستنې: په نړیوال لېست کې اسعار ولټوئ او فعال یا غیرفعال یې کړئ.",
    baseCurrency: "اصلي اسعار",
    searchCurrency: "اسعار پیدا کول",
    searchCurrencyPlaceholder: "کوډ یا نوم؛ لکه CNY",
    usedInShop: "په صرافۍ کې کارېږي",
    currencyOwnerHelp: "دا لېست مالک اداره کوي. فعال اسعار په ورځنیو فورمو کې ښکاري؛ د اسعارو معامله بیا هم تأیید شوي نرخ ته اړتیا لري.",
    ownerOnlyCurrencies: "یوازې مالک د صرافۍ د اسعارو لېست بدلولی شي.",
    currencyUpdated: "د صرافۍ د اسعارو لېست تازه شو.",
    currencyUpdateFailed: "دا بدلون خوندي نه شو. هغه اسعار چې موجودي لري، بندېدای نه شي.",
    addWorldCurrency: "بل نړیوال اسعار زیاتول",
    chooseWorldCurrency: "د اسعارو له نړیوال لېست څخه وټاکئ",
    sourceAccount: "پیسې له دې حسابه راځي",
    destinationAccount: "پیسې دې حساب ته ځي",
    chooseMoneyAccount: "د پیسو حساب وټاکئ",
    chooseSourceAccount: "سرچینه حساب وټاکئ",
    chooseDestinationAccount: "مقصد حساب وټاکئ",
    accountsMustDiffer: "د لېږد لپاره دوه بېل حسابونه وټاکئ.",
    valueInBaseCurrency: "په افغانیو ارزښت",
    baseValueHelp: "هغه افغاني ارزښت ولیکئ چې په دفتر کې کارېږي. د بېلابېلو اسعارو پیسې له ارزونې پرته نه جمع کېږي.",
    customerOutside: "پېرودونکی یا له صرافۍ بهر کس",
    outsideAccount: "له صرافۍ بهر حساب",
    openingFundsSource: "د کار پیل پانګه",
    incomeSource: "د عاید سرچینه",
    expenseDestination: "لګښت",
    ownerPersonal: "د مالک شخصي پیسې",
    activeCashboxAccount: "فعال صندوق",
    tradeMoneyFlow: "په دې معامله کې کارېدونکي حسابونه",
    tradeHasTwoMoneySides: "بهرني اسعار او افغانۍ په مخالفو لورو ځي. دواړه خواوې په ټاکل شوي صندوق کې ثبتېږي.",
    noCurrentRate: "اوسنی نرخ نشته",
    setShopRate: "د صرافۍ تأیید شوی نرخ ټاکل",
    setShopRateIntro: "ولیکئ چې د ټاکل شوو اسعارو یو واحد څو افغانۍ کېږي. پخوانی نرخ په تاریخچه کې پاتې کېږي.",
    foreignCurrency: "بهرني اسعار",
    ratePerUnitPlaceholder: "د یوه واحد افغاني ارزښت",
    saveShopRate: "تأیید شوی نرخ خوندي کول",
    ownerOnlyRates: "یوازې مالک د صرافۍ تأیید شوی نرخ ټاکلی شي.",
    rateSaved: "تأیید شوی نرخ خوندي شو.",
    rateSaveFailed: "نرخ خوندي نه شو. دواړه اسعار فعال او شمېرې وګورئ.",
    addEmployee: "کارکوونکی زیاتول",
    addEmployeeIntro: "کارکوونکی راوبلئ او په کره ډول وټاکئ چې په کومه څانګه او صندوق کې کار کولای شي.",
    fullName: "بشپړ نوم",
    workEmail: "کاري برېښنالیک",
    employeeRole: "دنده",
    branchAccess: "اجازه لرونکې څانګې",
    cashboxAccess: "اجازه لرونکي صندوقونه",
    businessWideAccess: "دا دنده ټولې صرافۍ ته لاسرسی لري.",
    cashierScopeRequired: "صندوق‌دار ته لږ تر لږه یوه څانګه او یو صندوق وټاکئ.",
    sendInvite: "بلنه جوړول",
    sendingInvite: "بلنه جوړېږي…",
    pendingInvitations: "پاتې بلنې",
    noPendingInvites: "کومه پاتې بلنه نشته.",
    inviteCreated: "بلنه چمتو شوه",
    inviteLinkInstructions: "دا شخصي لینک کاپي او کارکوونکي ته یې واستوئ. لینک ۷۲ ساعته وروسته پای ته رسېږي.",
    copyInviteLink: "د بلنې لینک کاپي کول",
    linkCopied: "د بلنې لینک کاپي شو.",
    emailInvite: "په برېښنالیک لېږل",
    expires: "د اعتبار پای",
    cancelInvite: "بلنه لغوه کول",
    editAccess: "لاسرسی بدلول",
    saveAccess: "لاسرسی ثبتول",
    suspendAccess: "لاسرسی درول",
    reactivateAccess: "لاسرسی بېرته فعالول",
    accessChangeReason: "د دې بدلون دلیل",
    cancelAction: "بېرته ګرځېدل",
    assignedTo: "ورسپارل شوی ځای",
    noSpecificScope: "ټولې صرافۍ ته لاسرسی",
    memberSince: "له دې نېټې غړی",
    invited: "بلل شوی",
    secureTeamAction: "دا خوندي کار تایید کړئ",
    secureTeamIntro: "د کارکوونکو د لاسرسي بدلون دوه پړاوه ننوتل غواړي، څو د پټنوم د غلا پر مهال صرافي خوندي پاتې شي.",
    setupAuthenticator: "رمزساز پروګرام برابرول",
    authenticatorInstructions: "دا کوډ په رمزساز پروګرام کې سکن کړئ، بیا شپږ رقمي کوډ ولیکئ.",
    authenticatorSecret: "د لاسي برابرولو کوډ",
    verificationCode: "شپږ رقمي کوډ",
    verifySecurity: "تایید او دوام",
    verifyingSecurity: "تاییدېږي…",
    securityVerified: "خوندي کار تایید شو.",
    mfaSetupFailed: "د رمزساز برابرول پیل نه شول. بیا هڅه وکړئ.",
    mfaVerificationFailed: "دا کوډ ونه منل شو. کوډ وګورئ او بیا هڅه وکړئ.",
    teamLoadFailed: "د کارکوونکو معلومات لوډ نه شول.",
    teamSaveFailed: "د کارکوونکي بدلون ثبت نه شو. معلومات وګورئ او بیا هڅه وکړئ.",
    joinTeam: "د صرافۍ له ټیم سره یوځای کېدل",
    joinTeamSubtitle: "په هغه برېښنالیک ننوځئ یا حساب جوړ کړئ چې بلنه ورته استول شوې ده.",
    createAndJoin: "حساب جوړول او یوځای کېدل",
    invitationAccepted: "بلنه ومنل شوه. ستاسو ټاکل شوی کاري ځای چمتو دی.",
    invitationInvalid: "د بلنې لینک ناسم دی یا نور اعتبار نه لري.",
    invitationExpired: "د دې بلنې وخت تېر شوی. له مالک څخه نوې بلنه وغواړئ.",
    invitationWrongAccount: "هماغه برېښنالیک وکاروئ چې مالک بللی دی.",
    signOutDifferentAccount: "وتل او بل حساب کارول",
    active: "فعال",
    suspended: "ځنډول شوی",
    accessOn: "لاس‌رسی لري",
    accessOff: "لاس‌رسی نه لري",
    extraSecurityRequired: "د ننوتلو اضافي امنیت اړین دی",
    normalSecurity: "د ننوتلو عادي امنیت",
    registeredDevices: "ثبت شوي وسایل",
    lastSeen: "وروستی فعالیت",
    revoked: "لغوه شوی",
    approvalInbox: "د تایید غوښتنې",
    approvalRequest: "د تایید غوښتنه",
    requested: "غوښتل شوی",
    review: "کتنه",
    noTeam: "تر اوسه کارکوونکی نه دی ورزیات شوی.",
    noDevices: "تر اوسه وسیله نه ده ثبت شوې.",
    deviceLinkFailed: "دا ویب وسیله ونه تړل شوه. د معاملې له ساتلو مخکې بیا هڅه وکړئ.",
    previewCustomer: "مخامخ پېرودونکی",
    platformAdministrator: "د سیستم عمومي مدیر",
    platformAdministratorSignIn: "د مدیر له جلا حساب سره ننوځئ. مالک او کارکوونکي له اصلي پاڼې ننوځي.",
    planPayment: "بسته او تادیه",
    addCustomer: "پېرودونکی زیاتول",
    customerName: "د پېرودونکي یا صراف نوم",
    customerType: "ډول",
    customerTypeCustomer: "پېرودونکی",
    customerTypeSaraf: "صراف",
    customerTypeHawala: "د حوالې همکار",
    customerTypeSupplier: "عرضه کوونکی",
    customerTypeEmployee: "کارکوونکی",
    phoneOptional: "د اړیکې شمېره (اختیاري)",
    saveCustomer: "پېرودونکی ساتل",
    customerCreated: "پېرودونکی وساتل شو او کارولو ته چمتو دی.",
    customerCreateFailed: "پېرودونکی ونه ساتل شو. نوم وګورئ او بیا هڅه وکړئ.",
    deviceAwaitingOwner: "دا ویب وسیله تړل شوې خو د مالک تایید ته منتظره ده. اوس معلومات لیدلی شئ؛ د پیسو حرکت ساتل له تایید وروسته خلاصېږي.",
    deviceTrusted: "تایید شوې",
    deviceWaiting: "تایید ته منتظره",
    deviceControlIntro: "د کارکوونکي نوې ویب وسیله د پیسو له ساتلو مخکې تایید کړئ. ورکه یا شریکه وسیله سمدستي لغوه کړئ.",
    deviceReasonRequired: "د وسیلې د بدلون لپاره لنډ لامل ولیکئ.",
    deviceReasonPlaceholder: "بېلګه: د صندوق کمپیوټر وکتل شو",
    approveDevice: "وسیله تاییدول",
    revokeDevice: "وسیله لغوه کول",
    deviceApproved: "وسیله تایید او چمتو شوه.",
    deviceRevoked: "د وسیلې لاسرسی لغوه شو.",
    moneyPlacesCount: "د پیسو ځایونه",
    roleHomeTitle_owner: "د مالک د کنترول مرکز",
    roleHomeDescription_owner: "ټوله صرافي، کارکوونکي، وسایل، تادیه او کنترولونه په یوه ځای کې وګورئ.",
    roleHomeTitle_manager: "ورځني کارونه",
    roleHomeDescription_manager: "څانګې او ورځنی کار پر مخ یوسئ او کاري غوښتنې وڅېړئ؛ د مالک ځانګړې امستنې جلا دي.",
    roleHomeTitle_accountant: "حسابونه او راپورونه",
    roleHomeDescription_accountant: "پاتې شوني، راپورونه او د صندوق کتنه وګورئ. دا دنده د پیسو حرکت نه ساتي.",
    roleHomeTitle_cashier: "زما د نن صندوق",
    roleHomeDescription_cashier: "یوازې درسپارل شوي صندوق پېرود، پلور، ترلاسه کول، ورکول او پای کتنه ترسره کړئ.",
    roleHomeTitle_compliance_officer: "د مقرراتو کتنه",
    roleHomeDescription_compliance_officer: "د پېرودونکي کتنه، خبرتیاوې، دوسیې او اړین اسناد پرته له معاملې ثبتولو وڅېړئ.",
    roleHomeTitle_viewer: "یوازې کتنه",
    roleHomeDescription_viewer: "تایید شوي پاتې شوني، راپورونه او د معاملو تاریخ پرته له بدلون څخه وګورئ.",
    customerLabel: "پېرودونکی",
    employeeLabel: "کارکوونکی",
    teamMember: "د ډلې غړی",
    weGaveLabel: "موږ ورکړل",
    weReceivedLabel: "موږ ترلاسه کړل",
    confirmPassword: "پټنوم بیا ولیکئ",
    fullNameRequired: "خپل بشپړ نوم ولیکئ.",
    passwordsDoNotMatch: "دواړه پټنومونه یو شان نه دي.",
    ownerSignupOnly: "نوې صرافي جوړول",
    workerUsesInvite: "یوازې مالک دلته نوې صرافي جوړوي. کارکوونکی د مالک د بلنې له لینک څخه حساب جوړوي یا ننوځي.",
    everyoneSignsInHere: "مالک، مدیر، صندوق‌دار، حسابدار، د مقرراتو مسؤل او کتونکی",
    signInRoleAutomatic: "ټول له همدې ځایه ننوځي. صرافي یوازې هغه دنده، څانګه او صندوق پرانیزي چې دې حساب ته سپارل شوي وي.",
    cashierCloseShortcut: "زما صندوق تړل",
    noApprovals: "د تایید غوښتنه نشته.",
    selfApprovalRule: "هیڅوک خپله غوښتنه نه شي تاییدولی.",
    accessRuleNote:
      "د اجازې، څانګې، صندوق، وسیلې او تایید قواعد د هر ثبت پر مهال په خپله کتل کېږي.",
    whereIsMoney: "زما پیسې چېرته دي؟",
    moneyIntro:
      "پیسې د اسعارو او ځای له مخې وګورئ؛ هر مبلغ له ثبت شوې معاملې سره تړلی دی.",
    allCurrencies: "ټول اسعار",
    currencyFirst: "د اسعارو له مخې",
    locationFirst: "د ځای له مخې",
    printSnapshot: "دا مخ چاپول",
    theyOweUs: "هغوی زموږ پوروړي دي",
    weOweThem: "موږ د هغوی پوروړي یو",
    postedRecords: "ثبت شوې معاملې",
    loadingMoney: "ستاسو پیسې لوډېږي…",
    totalCurrency: "د همدې اسعارو ټول مبلغ",
    moneyAtPlace: "په دې ځای کې پیسې · د جزیاتو لپاره یې پرانیزئ",
    noMoney: "تر اوسه پیسې نه دي ثبت شوې. پیل پیسې یا یوه معامله ثبت کړئ.",
    amountSource: "دا مبلغ له کومه راغلی",
    eachAmountSource: "هر مبلغ له یوې ثبت شوې معاملې سره تړلی دی.",
    selectLocation: "یو ځای وټاکئ چې د هغه د مبلغ اړوند معاملې وګورئ.",
    recordedTransaction: "ثبت شوې معامله",
    peopleTitle: "پېرودونکي او صرافان",
    peopleIntro:
      "یو کس ومومئ او په روښانه ډول وګورئ چې هغه ستاسو پوروړی دی که تاسو د هغه.",
    searchPeople: "پېرودونکی یا صراف ولټوئ",
    searchPeoplePlaceholder: "نوم یا د ټیلیفون شمېره",
    viewStatement: "حساب کتل",
    noPeopleMatch: "له دې لټون سره څوک ونه موندل شو.",
    statement: "حساب",
    balancesStaySeparate: "هر اسعار جلا ساتل کېږي چې مبلغ روښانه پاتې شي.",
    closeStatement: "حساب تړل",
    documents: "د پېژندنې اسناد",
    documentType: "د سند ډول",
    tazkira: "تذکره",
    passport: "پاسپورټ",
    customerPhoto: "د پېرودونکي عکس",
    preview: "کتل",
    due: "د ورکړې نېټه",
    captureUpload: "عکس واخلئ یا پورته یې کړئ",
    noDocuments: "د دې کس لپاره د پېژندنې سند نه دی ورزیات شوی.",
    balanceDetails: "د پور جزیات",
    noOutstanding: "دا کس نه‌ورکړل شوی پور نه لري.",
    statementHistory: "تاریخچه",
    noStatementHistory: "د دې کس لپاره فعالیت نه دی ثبت شوی.",
    transactionHistory: "د معاملو تاریخچه",
    transactionIntro: "وګورئ څه، کله او په کوم حالت کې ترسره شوي دي.",
    noTransactions:
      "تر اوسه معامله نه ده ثبت شوې. له «نوې معامله» څخه پیل وکړئ.",
    correction: "سمون",
    correctTransaction: "معامله سمول",
    originalReference: "د اصلي معاملې شمېره",
    correctionReason: "ولې دا معامله سمون غواړي؟",
    submitCorrection: "د سمون غوښتنه لېږل",
    ratesTitle: "د صرافۍ نرخونه",
    ratesIntro: "د پېرود او پلور اوسني مجاز نرخونه او پخواني بدلونونه.",
    rateHistory: "د نرخ تاریخچه",
    shopDefault: "د صرافۍ عمومي نرخ",
    branchRate: "د څانګې نرخ",
    effectiveFrom: "له دې وخته کارول شوی",
    noRateHistory: "تر اوسه مجاز نرخ نه دی ورزیات شوی.",
    calculatorNote:
      "محاسبه‌ګر یوازې مخکتنه ده. معامله یوازې ستاسو له تایید وروسته ثبتېږي.",
    reportsTitle: "راپورونه",
    reportsIntro: "د ګټې، پیسو، معاملو او پېرودونکو راپورونه چمتو کړئ.",
    reportType: "د راپور ډول",
    reportDaily: "ټول عملیات",
    reportFx: "د اسعارو معاملې",
    reportCash: "د پیسو خوځښتونه",
    reportDebt: "پورونه او ورکړې",
    reportLoading: "د دفتر ټول ثبتونه لوډېږي…",
    from: "له",
    to: "تر",
    all: "ټول",
    printA4: "A4 چاپ",
    print58: "۵۸ ملي‌متر چاپ",
    print80: "۸۰ ملي‌متر چاپ",
    shareWhatsApp: "په واټس‌اپ کې لېږل",
    reportsReady: "معاملې د صادرولو لپاره چمتو دي.",
    noReportRows: "له دې فلټرونو سره معامله ونه موندل شوه.",
    debtsTitle: "پورونه",
    debtsIntro: "ثبت کړئ چې څوک ستاسو پوروړی دی او تاسو د چا پوروړي یاست.",
    choosePerson: "یو پېرودونکی یا صراف وټاکئ",
    postDebt: "پور ثبتول",
    posting: "ثبتېږي…",
    noDebts:
      "نه‌ورکړل شوی پور نشته. یوازې هغه وخت یې ورزیات کړئ چې رښتیا پور وي.",
    settleDebt: "د پور ورکړه ثبتول",
    remaining: "پاتې",
    paymentAmount: "د ورکړې مبلغ",
    savePayment: "ورکړه ثبتول",
    settlementNote: "ورکړه پاتې مبلغ کموي او په تاریخچه کې ښکاري.",
    cashboxTitle: "صندوق کتل",
    cashboxIntro: "شمېرل شوې نغدې د صرافي له تمه شوي مبلغ سره پرتله کړئ.",
    expected: "تمه شوی",
    counted: "شمېرل شوی",
    difference: "توپیر",
    loading: "لوډېږي…",
    differenceReason: "د توپیر دلیل",
    reasonRequired: "د کمو یا زیاتو پیسو دلیل ولیکئ",
    submitCashCount: "د صندوق شمېر د کتنې لپاره لېږل",
    cashDifferenceNote:
      "کمې یا زیاتې پیسې د مجاز کس تر کتنې پورې ښکاره پاتې کېږي.",
    hawalaTitle: "حواله",
    hawalaIntro: "د پیسو اخیستونکی، ځای، مبلغ، کمېشن او د حوالې شمېره ثبت کړئ.",
    fullBeneficiaryName: "د اخیستونکي بشپړ نوم",
    cityCountry: "ښار یا هېواد",
    uniqueReference: "ځانګړې حواله شمېره",
    noHawala: "تر اوسه حواله نه ده ثبت شوې.",
    compliance: "د اصولو کتنه",
    recentActivity: "وروستی فعالیت",
    traceable: "د پیسو هر حرکت ثبتېږي او د کتنې وړ وي.",
    tradeReference: "معامله",
    viewTradeDetails: "د معاملې جزیات کتل",
    detailsAfterSync:
      "د معاملې جزیات د تازه معلوماتو له لوډېدو وروسته موندل کېږي.",
    couldNotLoad: "دا معلومات لوډ نه شول. بیا هڅه وکړئ.",
    couldNotSave: "دا کړنه ثبت نه شوه. معلومات وګورئ او بیا هڅه وکړئ.",
    savedSuccessfully: "په بریالیتوب ثبت شو.",
    businessSetupRequired: "د دې کړنې له ثبتولو مخکې د صرافۍ امستنې بشپړې کړئ.",
    activeBranchRequired: "د دې کړنې له ثبتولو مخکې فعاله څانګه وټاکئ.",
    activeCashboxRequired: "د دې کړنې له ثبتولو مخکې فعال صندوق وټاکئ.",
    connectionRequired: "د دې کړنې له ثبتولو مخکې انټرنېټ سره بیا ونښلئ.",
    amountGreaterZero: "له صفر څخه لوی مبلغ ولیکئ.",
    exportUnavailable: "دا راپور اوس نه شي صادرېدای.",
    exportReady: "راپور چمتو دی.",
    reversed: "سمون شوی",
    requestFailed: "دا غوښتنه بشپړه نه شوه. بیا هڅه وکړئ.",
    authInvalidCredentials: "برېښنالیک یا پټنوم سم نه دی.",
    authEmailNotConfirmed: "له ننوتلو مخکې خپل برېښنالیک تایید کړئ.",
    authTooManyAttempts: "ډېرې هڅې شوې دي. لږ صبر وکړئ او بیا هڅه وکړئ.",
    authRequestTimedOut: "د خوندي ننوتلو خدمت پر وخت ځواب ورنه کړ. بیا هڅه وکړئ.",
    authServiceUnreachable: "د خوندي ننوتلو له خدمت سره اړیکه ونه نیول شوه. خپل انټرنېټ وګورئ او بیا هڅه وکړئ.",
    authConfigurationError: "د خوندي ننوتلو خدمت سم نه دی تنظیم شوی. له خپل مسؤول سره اړیکه ونیسئ.",
    afghanAfghani: "افغانۍ",
    device: "وسیله",
    approved: "تایید شوی",
    rejected: "نه دی تایید شوی",
    documentSaved: "د پېژندنې سند په خوندي ډول ثبت شو.",
    shareOpened: "واټس‌اپ د دې راپور لېږلو ته چمتو دی.",
    direction: "څوک د چا پوروړی دی؟",
    person: "پېرودونکی یا صراف",
    counterparty: "پېرودونکی یا صراف",
    choosePersonFirst: "د پور له ثبتولو مخکې پېرودونکی یا صراف وټاکئ.",
    settling: "ثبتېږي…",
    outstanding: "پاتې مبلغ",
    expectedVsCounted: "تمه شوې او شمېرل شوې پیسې",
    countedAmount: "شمېرل شوې پیسې",
    expectedAmount: "تمه شوی مبلغ",
    variance: "توپیر",
    submitting: "لېږل کېږي…",
    optionalSection: "اختیاري خدمت",
    receiver: "اخیستونکی",
    amountAfn: "مبلغ (افغانۍ)",
    feeAfn: "کمېشن (افغانۍ)",
    postingHawala: "ثبتېږي…",
    hawalaBaseAmount: "په افغانیو د مبلغ ارزښت",
    hawalaFeeBaseAmount: "په افغانیو د فیس ارزښت",
    hawalaCustomer: "د حوالې پېرودونکی",
    saveHawala: "حواله ثبتول",
    languageNameEnglish: "انګلیسي",
    languageNameDari: "دري",
    languageNamePashto: "پښتو",
    firstSetup: "د صرافۍ لومړنۍ امستنې",
    setupTitle: "خپله صرافي جوړه کړئ",
    setupIntro:
      "د صرافۍ له اړینو معلوماتو پیل وکړئ. پرمختللې امستنې وروسته بدلولی شئ.",
    businessNameQuestion: "ستاسو د صرافۍ نوم څه دی؟",
    businessNamePlaceholder: "سروري صرافي",
    mainBranchName: "د اصلي څانګې نوم",
    mainBranchPlaceholder: "مرکزي څانګه",
    currenciesQuestion: "کوم اسعار کاروئ؟",
    mainCashboxName: "د اصلي صندوق نوم",
    mainCashboxPlaceholder: "اصلي صندوق",
    startingCurrency: "اصلي اسعار",
    selectedCurrencies: "ټاکل شوي اسعار",
    nextStep: "بل ګام",
    onboardingNext: "پیل پیسې ورزیاتې او بیا خپله لومړۍ معامله ثبت کړئ",
    firstDayTitle: "د لومړۍ ورځې امستنې بشپړې کړئ",
    firstDayIntro: "څلور لنډ ګامونه صرافي ورځني کار ته چمتو کوي.",
    creatingBusiness: "صرافي جوړېږي…",
    createBusiness: "زما صرافي جوړول",
    switchingShop: "پخواني معلومات لېږدول",
    importCenter: "د معلوماتو د لېږد مرکز",
    importIntro: "د پېرودونکو، پیل پیسو یا پورونو له ثبتولو مخکې فایل وګورئ.",
    importType: "کوم معلومات لېږدوئ؟",
    counterparties: "پېرودونکي او صرافان",
    openingBalances: "پیل پیسې",
    downloadTemplate: "د CSV نمونه ښکته کول",
    chooseCsv: "CSV فایل ټاکل",
    previewComplete: "د فایل کتنه بشپړه شوه. معلومات نه دي بدل شوي.",
    csvReadFailed: "دا CSV فایل ونه لوستل شو. نمونه وګورئ او بیا هڅه وکړئ.",
    rowsChecked: "کتل شوي کتارونه",
    issues: "ستونزې",
    readyToImport: "لېږد ته چمتو",
    yes: "هو",
    no: "نه",
    total: "ټول",
    row: "کتار",
    fixRequired: "سمون اړین دی",
    importReady:
      "کتل شوی فایل چمتو دی. یوازې د معلوماتو له ډاډ وروسته یې تایید کړئ.",
    confirmImport: "لېږد تاییدول",
    importSaved: "توکي په بریالیتوب ولېږدول شول.",
    reviewTransaction: "معامله کتل",
    confirmTransaction: "تایید او ثبتول",
    editTransaction: "معامله سمول",
    confirmationTitle: "له ثبتولو مخکې یې وګورئ",
    confirmationIntro: "تایید کړئ چې صرافي همدا مبلغونه ورکوي او ترلاسه کوي.",
    pairRateUnavailable:
      "د دې اسعارو جوړې لپاره تایید شوی نرخ نشته. له تبادلې مخکې له واک لرونکي کس څخه وغواړئ چې نرخ ثبت کړي.",
    addDebt: "پور ثبتول",
    postingPaused: "د انټرنېټ تر بېرته راتګ پورې مالي ثبت درول شوی.",
    retry: "بیا هڅه",
    sourceCurrency: "د محاسبې اصلي اسعار",
    targetCurrency: "د محاسبې ترلاسه کېدونکي اسعار",
    moreBusiness: "راپورونه، نرخونه او صندوقونه",
    moreTeam: "کارکوونکي، تاییدونه او وسایل",
    moreSettings: "د صرافۍ او امنیت امستنې",
    moreAdvanced: "معلومات لېږدول، حواله او څارنه",
  },
} as const;

export type UxCopyKey = keyof typeof copy.en;

export function ux(language: Language, key: UxCopyKey): string {
  return copy[language][key] ?? copy.en[key];
}
