import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { parseDebtCreateCommand, parseDebtSettlementCommand } from './domain/commands'

const migration = readFileSync(new URL('../supabase/migrations/20260909224920_human_ids_subscriptions_and_search.sql', import.meta.url), 'utf8')
const app = readFileSync(new URL('./App.tsx', import.meta.url), 'utf8')
const exportsSource = readFileSync(new URL('./lib/exports.ts', import.meta.url), 'utf8')

describe('operational upgrade v7 contracts', () => {
  it('keeps UUID keys internal while exposing stable numeric references', () => {
    expect(migration).toContain('user_number bigint generated by default as identity')
    expect(migration).toContain('customer_number bigint generated by default as identity')
    expect(migration).toContain('transaction_number bigint generated by default as identity')
    expect(migration).toContain("'T-' || lpad(je.transaction_number::text, 8, '0')")
    expect(migration).toContain("'C-' || lpad(cp.customer_number::text, 8, '0')")
  })

  it('supports four priced subscription terms with protected reads', () => {
    expect(migration).toContain('term_months in (1, 3, 6, 12)')
    expect(migration).toContain('alter table public.subscription_plan_prices enable row level security')
    expect(migration).toContain('published_subscription_price_read')
    expect(migration).toContain('make_interval(months => request_row.term_months)')
  })

  it('searches transactions and customers by their human references', () => {
    expect(migration).toContain('search_transaction_history_v7')
    expect(migration).toContain('search_counterparties_v7')
    expect(app).toContain('Find transaction or customer ID')
    expect(app).toContain('transaction-receipt')
  })

  it('passes cashbox scope through debt create and settlement commands', () => {
    const common = {
      amount: '10',
      cashbox_id: '44444444-4444-4444-8444-444444444444',
      client_command_id: 'test-command',
    }
    expect(parseDebtCreateCommand({
      ...common,
      organization_id: '11111111-1111-4111-8111-111111111111',
      branch_id: '22222222-2222-4222-8222-222222222222',
      counterparty_id: '33333333-3333-4333-8333-333333333333',
      direction: 'receivable',
      currency: 'AFN',
      source_money_account_id: '55555555-5555-4555-8555-555555555555',
    }).cashbox_id).toBe(common.cashbox_id)
    expect(parseDebtSettlementCommand({
      ...common,
      debt_id: '66666666-6666-4666-8666-666666666666',
      destination_money_account_id: '55555555-5555-4555-8555-555555555555',
    }).cashbox_id).toBe(common.cashbox_id)
  })

  it('uses the shop ledger for its rate board without an external source', () => {
    expect(app).toContain('listRateHistory(organizationId)')
    expect(app).not.toContain('getSarafiAfRateBoard')
  })

  it('does not truncate daily PDF rows', () => {
    expect(exportsSource).not.toContain('input.rows.slice(0, 12)')
    expect(exportsSource).not.toContain('input.rows.slice(0, 8)')
    expect(app).not.toContain('Reason for the rate decision')
  })
})
