-- Explicit read policies for the inventory-completion entities. Financial writes remain RPC-only.
create policy organization_settings_member_read on public.organization_settings for select using (public.is_org_member(organization_id));
create policy organization_features_member_read on public.organization_features for select using (public.is_org_member(organization_id));
create policy profiles_self_read on public.profiles for select using (id = auth.uid());
create policy memberships_member_read on public.organization_memberships for select using (public.is_org_member(organization_id));
create policy scopes_member_read on public.membership_scopes for select using (exists (select 1 from public.organization_memberships m where m.id = membership_id and public.is_org_member(m.organization_id)));
create policy trusted_devices_member_read on public.trusted_devices for select using (exists (select 1 from public.devices d where d.id = device_id and public.is_org_member(d.organization_id)));
create policy auth_security_member_read on public.auth_security_events for select using (organization_id is null or public.is_org_member(organization_id));
create policy support_grants_owner_read on public.support_access_grants for select using (public.has_org_permission(organization_id, 'security:manage'));
create policy safes_member_read on public.safes for select using (public.is_org_member(organization_id));
create policy bank_accounts_member_read on public.bank_accounts for select using (public.is_org_member(organization_id));
create policy chart_accounts_member_read on public.chart_of_accounts for select using (organization_id is null or public.is_org_member(organization_id));
create policy source_events_member_read on public.source_events for select using (public.is_org_member(organization_id));
create policy command_idempotency_member_read on public.command_idempotency for select using (public.is_org_member(organization_id));
create policy reversals_member_read on public.reversals for select using (public.is_org_member(organization_id));
create policy accounting_periods_member_read on public.accounting_periods for select using (public.is_org_member(organization_id));
create policy fx_trades_member_read on public.fx_trades for select using (public.is_org_member(organization_id));
create policy fx_trade_legs_member_read on public.fx_trade_legs for select using (exists (select 1 from public.fx_trades t where t.id = trade_id and public.is_org_member(t.organization_id)));
create policy fees_member_read on public.fees for select using (public.is_org_member(organization_id));
create policy bank_movements_member_read on public.bank_movements for select using (public.is_org_member(organization_id));
create policy income_events_member_read on public.income_events for select using (public.is_org_member(organization_id));
create policy owner_capital_member_read on public.owner_capital_events for select using (public.is_org_member(organization_id));
create policy settlements_member_read on public.settlements for select using (public.is_org_member(organization_id));
create policy attachments_member_read on public.attachments for select using (public.is_org_member(organization_id));
create policy contacts_member_read on public.counterparty_contacts for select using (public.is_org_member(organization_id));
create policy addresses_member_read on public.counterparty_addresses for select using (public.is_org_member(organization_id));
create policy tags_member_read on public.counterparty_tags for select using (exists (select 1 from public.counterparties c where c.id = counterparty_id and public.is_org_member(c.organization_id)));
create policy credit_limits_member_read on public.counterparty_credit_limits for select using (public.is_org_member(organization_id));
create policy counterparty_docs_member_read on public.counterparty_documents for select using (public.is_org_member(organization_id));
create policy cost_state_member_read on public.fx_inventory_cost_state for select using (public.is_org_member(organization_id));
create policy position_snapshots_member_read on public.currency_position_snapshots for select using (public.is_org_member(organization_id));
create policy shifts_member_read on public.shifts for select using (public.is_org_member(organization_id));
create policy closures_member_read on public.cashbox_closures for select using (public.is_org_member(organization_id));
create policy cash_counts_member_read on public.cash_counts for select using (public.is_org_member(organization_id));
create policy cash_count_lines_member_read on public.cash_count_lines for select using (exists (select 1 from public.cash_counts c where c.id = cash_count_id and public.is_org_member(c.organization_id)));
create policy cash_variances_member_read on public.cash_variances for select using (public.is_org_member(organization_id));
create policy compliance_profiles_member_read on public.compliance_profiles for select using (public.has_org_permission(organization_id, 'compliance:review'));
create policy compliance_rules_member_read on public.compliance_rules for select using (exists (select 1 from public.compliance_rule_sets r where r.id = rule_set_id and public.has_org_permission(r.organization_id, 'compliance:review')));
create policy screening_runs_member_read on public.screening_runs for select using (public.has_org_permission(organization_id, 'compliance:review'));
create policy screening_matches_member_read on public.screening_matches for select using (exists (select 1 from public.screening_runs r where r.id = screening_run_id and public.has_org_permission(r.organization_id, 'compliance:review')));
create policy regulatory_runs_member_read on public.regulatory_report_runs for select using (public.has_org_permission(organization_id, 'compliance:review'));
create policy regulatory_exports_member_read on public.regulatory_report_exports for select using (exists (select 1 from public.regulatory_report_runs r where r.id = report_run_id and public.has_org_permission(r.organization_id, 'compliance:review')));
create policy compliance_audit_member_read on public.compliance_audit_events for select using (public.has_org_permission(organization_id, 'compliance:review'));
create policy hawala_partners_member_read on public.hawala_partners for select using (public.is_org_member(organization_id));
create policy hawala_beneficiaries_member_read on public.hawala_beneficiaries for select using (public.is_org_member(organization_id));
create policy hawala_status_member_read on public.hawala_status_events for select using (exists (select 1 from public.hawala_transfers h where h.id = transfer_id and public.is_org_member(h.organization_id)));
create policy hawala_settlements_member_read on public.hawala_settlements for select using (public.is_org_member(organization_id));
create policy roles_read on public.roles for select using (true);
create policy permissions_read on public.permissions for select using (true);
create policy role_permissions_read on public.role_permissions for select using (true);
