-- Complete the required SARAFI domain inventory without weakening existing immutable tables.
create table if not exists public.organization_settings (organization_id uuid primary key references public.organizations(id) on delete cascade, default_language text not null default 'en', base_currency_code text not null default 'AFN' references public.currencies(code), negative_cash_allowed boolean not null default false, offline_limit_base numeric(38,12) not null default 0, receipt_prefix text not null default 'SAR', timezone text not null default 'Asia/Kabul', updated_at timestamptz not null default now());
create table if not exists public.organization_features (organization_id uuid not null references public.organizations(id) on delete cascade, feature_code text not null, enabled boolean not null default false, updated_at timestamptz not null default now(), primary key (organization_id, feature_code));
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, phone text, preferred_language text not null default 'en', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.roles (code text primary key, label text not null);
create table if not exists public.permissions (code text primary key, label text not null);
create table if not exists public.role_permissions (role_code text not null references public.roles(code) on delete cascade, permission_code text not null references public.permissions(code) on delete cascade, primary key (role_code, permission_code));
create table if not exists public.membership_scopes (membership_id uuid not null references public.organization_memberships(id) on delete cascade, branch_id uuid references public.branches(id) on delete cascade, cashbox_id uuid references public.cashboxes(id) on delete cascade, primary key (membership_id, branch_id, cashbox_id));
create table if not exists public.trusted_devices (device_id uuid primary key references public.devices(id) on delete cascade, trusted_by uuid not null references auth.users(id), trusted_at timestamptz not null default now());
create table if not exists public.auth_security_events (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id), user_id uuid references auth.users(id), device_id uuid references public.devices(id), event_type text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.support_access_grants (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, support_user_id uuid not null references auth.users(id), approved_by uuid references auth.users(id), reason text not null, scope text[] not null default '{}', expires_at timestamptz not null, revoked_at timestamptz, created_at timestamptz not null default now());

create table if not exists public.safes (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, branch_id uuid not null references public.branches(id), name text not null, active boolean not null default true);
create table if not exists public.bank_accounts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, branch_id uuid references public.branches(id), bank_name text not null, account_name text not null, account_reference text, active boolean not null default true);
create table if not exists public.chart_of_accounts (id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id) on delete cascade, code text not null, name text not null, category text not null, system_account boolean not null default false, unique (organization_id, code));
create table if not exists public.source_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, source_type text not null, source_reference text not null, payload jsonb not null default '{}', created_at timestamptz not null default now(), unique (organization_id, source_type, source_reference));
create table if not exists public.command_idempotency (organization_id uuid not null references public.organizations(id) on delete cascade, client_command_id text not null, command_type text not null, response jsonb, created_at timestamptz not null default now(), primary key (organization_id, client_command_id));
create table if not exists public.reversals (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, original_entry_id uuid not null references public.journal_entries(id), reversal_entry_id uuid references public.journal_entries(id), reason text not null, requested_by uuid not null references auth.users(id), approved_by uuid references auth.users(id), created_at timestamptz not null default now(), unique (original_entry_id));
create table if not exists public.accounting_periods (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, starts_on date not null, ends_on date not null, status text not null default 'open' check (status in ('open', 'closed')), unique (organization_id, starts_on, ends_on), check (starts_on <= ends_on));

create table if not exists public.fx_trades (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, branch_id uuid not null references public.branches(id), counterparty_id uuid references public.counterparties(id), side text not null check (side in ('buy', 'sell', 'exchange')), rate_group_id uuid, customer_rate numeric(38,18) not null, fee_id uuid, journal_entry_id uuid references public.journal_entries(id), created_at timestamptz not null default now());
create table if not exists public.fx_trade_legs (id uuid primary key default gen_random_uuid(), trade_id uuid not null references public.fx_trades(id) on delete cascade, currency_code text not null references public.currencies(code), direction text not null check (direction in ('gives', 'receives')), amount numeric(38,12) not null check (amount > 0), location text not null);
create table if not exists public.fees (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, amount numeric(38,12) not null check (amount >= 0), currency_code text not null references public.currencies(code), direction text not null check (direction in ('income', 'expense')), journal_entry_id uuid references public.journal_entries(id));
create table if not exists public.bank_movements (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, branch_id uuid not null references public.branches(id), from_location text not null, to_location text not null, currency_code text not null references public.currencies(code), amount numeric(38,12) not null check (amount > 0), journal_entry_id uuid references public.journal_entries(id));
create table if not exists public.income_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, branch_id uuid not null references public.branches(id), category text not null, currency_code text not null references public.currencies(code), amount numeric(38,12) not null check (amount > 0), journal_entry_id uuid references public.journal_entries(id));
create table if not exists public.owner_capital_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, owner_id uuid not null references auth.users(id), event_type text not null check (event_type in ('investment', 'withdrawal')), currency_code text not null references public.currencies(code), amount numeric(38,12) not null check (amount > 0), journal_entry_id uuid references public.journal_entries(id));
create table if not exists public.settlements (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, counterparty_id uuid not null references public.counterparties(id), debt_id uuid references public.debts(id), direction text not null check (direction in ('receivable', 'payable')), currency_code text not null references public.currencies(code), amount numeric(38,12) not null check (amount > 0), journal_entry_id uuid references public.journal_entries(id), created_at timestamptz not null default now());
create table if not exists public.attachments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, entity_type text not null, entity_id uuid not null, storage_path text not null, content_type text not null, size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 5242880), sha256 text not null, uploaded_by uuid not null references auth.users(id), created_at timestamptz not null default now());

create table if not exists public.counterparty_contacts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, counterparty_id uuid not null references public.counterparties(id) on delete cascade, contact_type text not null, value text not null);
create table if not exists public.counterparty_addresses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, counterparty_id uuid not null references public.counterparties(id) on delete cascade, address_text text not null);
create table if not exists public.counterparty_tags (counterparty_id uuid not null references public.counterparties(id) on delete cascade, tag text not null, primary key (counterparty_id, tag));
create table if not exists public.counterparty_credit_limits (organization_id uuid not null references public.organizations(id) on delete cascade, counterparty_id uuid not null references public.counterparties(id) on delete cascade, currency_code text not null references public.currencies(code), limit_amount numeric(38,12) not null check (limit_amount >= 0), primary key (counterparty_id, currency_code));
create table if not exists public.counterparty_documents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, counterparty_id uuid not null references public.counterparties(id) on delete cascade, storage_path text not null, document_type text not null, created_at timestamptz not null default now());

create table if not exists public.fx_inventory_cost_state (organization_id uuid not null references public.organizations(id) on delete cascade, currency_code text not null references public.currencies(code), quantity numeric(38,12) not null default 0, carrying_base_value numeric(38,12) not null default 0, updated_at timestamptz not null default now(), primary key (organization_id, currency_code));
create table if not exists public.currency_position_snapshots (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, snapshot_date date not null, currency_code text not null references public.currencies(code), native_quantity numeric(38,12) not null, receivable_quantity numeric(38,12) not null, payable_quantity numeric(38,12) not null, carrying_base_value numeric(38,12) not null, valuation_base_value numeric(38,12) not null, realized_profit numeric(38,12) not null default 0, unrealized_change numeric(38,12) not null default 0, unique (organization_id, snapshot_date, currency_code));

create table if not exists public.shifts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, branch_id uuid not null references public.branches(id), cashbox_id uuid not null references public.cashboxes(id), opened_by uuid not null references auth.users(id), opened_at timestamptz not null default now(), closed_at timestamptz, status text not null default 'open' check (status in ('open', 'closed')));
create table if not exists public.cashbox_closures (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, shift_id uuid references public.shifts(id), cashbox_id uuid not null references public.cashboxes(id), closed_by uuid not null references auth.users(id), status text not null default 'submitted' check (status in ('submitted', 'approved', 'rejected')), created_at timestamptz not null default now());
create table if not exists public.cash_counts (id uuid primary key default gen_random_uuid(), closure_id uuid not null references public.cashbox_closures(id) on delete cascade, organization_id uuid not null references public.organizations(id) on delete cascade, currency_code text not null references public.currencies(code), expected_amount numeric(38,12) not null, counted_amount numeric(38,12) not null, variance_amount numeric(38,12) generated always as (counted_amount - expected_amount) stored);
create table if not exists public.cash_count_lines (id uuid primary key default gen_random_uuid(), cash_count_id uuid not null references public.cash_counts(id) on delete cascade, denomination numeric(38,12) not null check (denomination > 0), quantity integer not null check (quantity >= 0));
create table if not exists public.cash_variances (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, closure_id uuid not null references public.cashbox_closures(id), currency_code text not null references public.currencies(code), amount numeric(38,12) not null, reason text, approval_id uuid references public.approval_requests(id));

create table if not exists public.compliance_profiles (organization_id uuid primary key references public.organizations(id) on delete cascade, profile_name text not null, legal_signoff_status text not null default 'awaiting_legal_signoff', reviewed_at timestamptz, reviewed_by text);
create table if not exists public.compliance_rules (id uuid primary key default gen_random_uuid(), rule_set_id uuid not null references public.compliance_rule_sets(id) on delete cascade, rule_code text not null, parameters jsonb not null default '{}', unique (rule_set_id, rule_code));
create table if not exists public.screening_runs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, provider_name text not null, source_version text not null, started_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.screening_matches (id uuid primary key default gen_random_uuid(), screening_run_id uuid not null references public.screening_runs(id) on delete cascade, counterparty_id uuid not null references public.counterparties(id), score numeric(8,6), details jsonb not null default '{}', resolution text);
create table if not exists public.regulatory_report_runs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, report_type text not null, rule_set_id uuid references public.compliance_rule_sets(id), status text not null default 'draft', generated_at timestamptz not null default now(), submitted_reference text, submitted_at timestamptz);
create table if not exists public.regulatory_report_exports (id uuid primary key default gen_random_uuid(), report_run_id uuid not null references public.regulatory_report_runs(id) on delete cascade, format text not null, storage_path text not null, created_at timestamptz not null default now());
create table if not exists public.compliance_audit_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, actor_user_id uuid references auth.users(id), action text not null, entity_type text not null, entity_id uuid, reason text, created_at timestamptz not null default now());

create table if not exists public.hawala_partners (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, counterparty_id uuid references public.counterparties(id), name text not null, active boolean not null default true);
create table if not exists public.hawala_beneficiaries (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, transfer_id uuid references public.hawala_transfers(id), name text not null, phone text);
create table if not exists public.hawala_status_events (id uuid primary key default gen_random_uuid(), transfer_id uuid not null references public.hawala_transfers(id) on delete cascade, status text not null, actor_user_id uuid references auth.users(id), created_at timestamptz not null default now());
create table if not exists public.hawala_settlements (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, transfer_id uuid not null references public.hawala_transfers(id), partner_id uuid not null references public.hawala_partners(id), currency_code text not null references public.currencies(code), amount numeric(38,12) not null check (amount > 0), journal_entry_id uuid references public.journal_entries(id));

insert into public.roles (code, label) values ('owner', 'Owner'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('cashier', 'Cashier'), ('viewer', 'Viewer / Auditor'), ('compliance_officer', 'Compliance Officer'), ('platform_admin', 'Platform Administrator') on conflict do nothing;
insert into public.permissions (code, label) values ('organization:manage', 'Manage organization'), ('financial:overview', 'View financial overview'), ('financial:post', 'Post financial commands'), ('financial:report', 'View reports'), ('reconciliation:manage', 'Manage reconciliation'), ('team:manage', 'Manage team'), ('approval:decide', 'Decide approvals'), ('compliance:review', 'Review compliance'), ('security:manage', 'Manage security') on conflict do nothing;

DO $$ declare table_name text; begin foreach table_name in array array['organization_settings','organization_features','profiles','roles','permissions','role_permissions','membership_scopes','trusted_devices','auth_security_events','support_access_grants','safes','bank_accounts','chart_of_accounts','source_events','command_idempotency','reversals','accounting_periods','fx_trades','fx_trade_legs','fees','bank_movements','income_events','owner_capital_events','settlements','attachments','counterparty_contacts','counterparty_addresses','counterparty_tags','counterparty_credit_limits','counterparty_documents','fx_inventory_cost_state','currency_position_snapshots','shifts','cashbox_closures','cash_counts','cash_count_lines','cash_variances','compliance_profiles','compliance_rules','screening_runs','screening_matches','regulatory_report_runs','regulatory_report_exports','compliance_audit_events','hawala_partners','hawala_beneficiaries','hawala_status_events','hawala_settlements'] loop execute format('alter table public.%I enable row level security', table_name); end loop; end $$;

create or replace view public.domain_inventory_status with (security_invoker = true) as
select 'tenancy_and_configuration' as domain, count(*)::integer as entity_count from public.organizations
union all select 'identity_and_authorization', count(*)::integer from public.organization_memberships
union all select 'ledger', count(*)::integer from public.journal_entries
union all select 'operations', count(*)::integer from public.fx_trades
union all select 'people', count(*)::integer from public.counterparties
union all select 'compliance', count(*)::integer from public.compliance_alerts;
