-- Human-facing identifiers, fixed-term subscription pricing, and searchable
-- transaction history. UUIDs remain the internal keys; these numbers are the
-- stable references shown to people and printed on receipts.

alter table public.profiles
  add column user_number bigint generated by default as identity;
alter table public.organizations
  add column business_number bigint generated by default as identity;
alter table public.counterparties
  add column customer_number bigint generated by default as identity;
alter table public.journal_entries
  add column transaction_number bigint generated by default as identity;

create unique index profiles_user_number_key on public.profiles (user_number);
create unique index organizations_business_number_key on public.organizations (business_number);
create unique index counterparties_customer_number_key on public.counterparties (customer_number);
create unique index journal_entries_transaction_number_key on public.journal_entries (transaction_number);
create index counterparties_org_customer_number_idx on public.counterparties (organization_id, customer_number);
create index journal_entries_org_transaction_number_idx on public.journal_entries (organization_id, transaction_number desc);

create table public.subscription_plan_prices (
  id bigint generated always as identity primary key,
  plan_id uuid not null references public.subscription_plans(id) on delete cascade,
  term_months smallint not null check (term_months in (1, 3, 6, 12)),
  price_afn numeric(18,2) not null check (price_afn > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (plan_id, term_months)
);

create index subscription_plan_prices_active_idx
  on public.subscription_plan_prices (plan_id, term_months)
  where active;

alter table public.subscription_plan_prices enable row level security;
create policy published_subscription_price_read
  on public.subscription_plan_prices
  for select to authenticated
  using (
    exists (
      select 1 from public.subscription_plans p
      where p.id = plan_id and (p.status = 'published' or (select public.is_platform_admin()))
    )
  );

revoke all on table public.subscription_plan_prices from public, anon, authenticated;
grant select on table public.subscription_plan_prices to authenticated;

insert into public.subscription_plan_prices (plan_id, term_months, price_afn)
select p.id, prices.term_months, prices.price_afn
from public.subscription_plans p
cross join lateral (
  values
    (1::smallint, p.price_afn),
    (3::smallint, round(p.price_afn * 2.85, 2)),
    (6::smallint, round(p.price_afn * 5.40, 2)),
    (12::smallint, round(p.price_afn * 10.00, 2))
) prices(term_months, price_afn)
where p.status in ('published', 'draft')
on conflict (plan_id, term_months) do update
set price_afn = excluded.price_afn, active = true, updated_at = now();

alter table public.subscription_payment_requests
  add column term_months smallint not null default 1
    check (term_months in (1, 3, 6, 12));

create or replace function public.get_billing_portal(target_org uuid)
returns jsonb
language plpgsql
security definer
stable
set search_path = ''
as $$
declare result jsonb;
begin
  if not exists (
    select 1 from public.organization_memberships
    where organization_id = target_org and user_id = (select auth.uid()) and active and role_code = 'owner'
  ) then raise exception 'Only the business owner can manage the plan'; end if;
  select jsonb_build_object(
    'subscription', (
      select jsonb_build_object(
        'id', s.id, 'status', s.status, 'trial_ends_at', s.trial_ends_at,
        'current_period_end', s.current_period_end, 'plan_id', p.id,
        'plan_code', p.code, 'plan_name_en', p.name_en,
        'plan_name_dari', p.name_dari, 'plan_name_pashto', p.name_pashto
      ) from public.organization_subscriptions s
        join public.subscription_plans p on p.id = s.plan_id
      where s.organization_id = target_org
    ),
    'plans', coalesce((
      select jsonb_agg(
        to_jsonb(p) || jsonb_build_object('term_prices', coalesce((
          select jsonb_agg(jsonb_build_object('term_months', pp.term_months, 'price_afn', pp.price_afn) order by pp.term_months)
          from public.subscription_plan_prices pp where pp.plan_id = p.id and pp.active
        ), '[]'::jsonb))
        order by p.sort_order, p.id
      ) from public.subscription_plans p where p.status = 'published'
    ), '[]'::jsonb),
    'providers', coalesce((select jsonb_agg(to_jsonb(pc) order by pc.code) from public.payment_provider_configs pc where pc.state = 'live'), '[]'::jsonb),
    'requests', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', r.id, 'plan_id', r.plan_id, 'provider_code', r.provider_code,
        'amount_afn', r.amount_afn, 'term_months', r.term_months,
        'payer_reference', r.payer_reference, 'status', r.status,
        'requested_at', r.requested_at, 'review_note', r.review_note
      ) order by r.requested_at desc)
      from public.subscription_payment_requests r where r.organization_id = target_org
    ), '[]'::jsonb)
  ) into result;
  return result;
end;
$$;

drop function if exists public.create_subscription_payment_request(uuid, uuid, text, text, text);
create function public.create_subscription_payment_request(
  target_org uuid,
  target_plan uuid,
  target_provider text,
  term_months_input smallint,
  payer_reference_input text,
  payer_note_input text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare plan_row public.subscription_plans;
declare provider_row public.payment_provider_configs;
declare subscription_row public.organization_subscriptions;
declare request_row public.subscription_payment_requests;
declare selected_price numeric(18,2);
begin
  if not exists (
    select 1 from public.organization_memberships
    where organization_id = target_org and user_id = (select auth.uid()) and active and role_code = 'owner'
  ) then raise exception 'Only the business owner can request plan activation'; end if;
  if term_months_input not in (1, 3, 6, 12) then raise exception 'Choose a valid subscription term'; end if;
  select * into plan_row from public.subscription_plans where id = target_plan and status = 'published';
  select pp.price_afn into selected_price from public.subscription_plan_prices pp
    where pp.plan_id = target_plan and pp.term_months = term_months_input and pp.active;
  if plan_row.id is null or selected_price is null then raise exception 'This plan and term are not available for payment'; end if;
  select * into provider_row from public.payment_provider_configs where code = target_provider and state = 'live';
  if provider_row.code is null then raise exception 'This payment method is not active'; end if;
  if provider_row.provider_mode = 'manual_review' and length(trim(coalesce(payer_reference_input, ''))) < 3 then
    raise exception 'Receipt reference is required';
  end if;
  select * into subscription_row from public.organization_subscriptions where organization_id = target_org for update;
  if subscription_row.id is null then raise exception 'Subscription was not found'; end if;
  insert into public.subscription_payment_requests (
    organization_id, subscription_id, plan_id, provider_code, amount_afn, term_months,
    payer_reference, payer_note, status, requested_by
  ) values (
    target_org, subscription_row.id, plan_row.id, provider_row.code, selected_price, term_months_input,
    nullif(trim(payer_reference_input), ''), nullif(trim(payer_note_input), ''),
    case when provider_row.provider_mode = 'manual_review' then 'submitted' else 'awaiting_payment' end,
    (select auth.uid())
  ) returning * into request_row;
  update public.organization_subscriptions set status = 'pending_payment', updated_at = now()
    where id = subscription_row.id and status not in ('active', 'suspended');
  return jsonb_build_object('request', to_jsonb(request_row), 'checkout_url', provider_row.public_checkout_url);
end;
$$;

create or replace function public.decide_subscription_payment(
  target_request uuid,
  decision text,
  review_note_input text
)
returns public.subscription_payment_requests
language plpgsql
security definer
set search_path = ''
as $$
declare request_row public.subscription_payment_requests;
declare next_end timestamptz;
begin
  perform public.require_platform_admin(true);
  if decision not in ('approved', 'rejected') then raise exception 'Choose approve or reject'; end if;
  if length(trim(coalesce(review_note_input, ''))) < 3 then raise exception 'Administrator note is required'; end if;
  select * into request_row from public.subscription_payment_requests where id = target_request for update;
  if request_row.id is null or request_row.status not in ('submitted', 'under_review') then
    raise exception 'Payment request is no longer available';
  end if;
  select greatest(coalesce(s.current_period_end, now()), now()) + make_interval(months => request_row.term_months)
    into next_end from public.organization_subscriptions s where s.id = request_row.subscription_id for update;
  update public.subscription_payment_requests set
    status = decision, reviewed_by = (select auth.uid()), reviewed_at = now(), review_note = trim(review_note_input)
    where id = target_request returning * into request_row;
  if decision = 'approved' then
    update public.organization_subscriptions set
      plan_id = request_row.plan_id, status = 'active', current_period_start = now(),
      current_period_end = next_end, activated_by = (select auth.uid()),
      suspension_reason = null, updated_at = now()
      where id = request_row.subscription_id;
  end if;
  insert into public.platform_audit_events (actor_user_id, event_type, target_organization_id, metadata)
    values ((select auth.uid()), 'subscription_payment_' || decision, request_row.organization_id,
      jsonb_build_object('request_id', request_row.id, 'amount_afn', request_row.amount_afn,
        'term_months', request_row.term_months, 'note', trim(review_note_input)));
  return request_row;
end;
$$;

create or replace function public.get_platform_organization_users(target_org uuid)
returns jsonb
language plpgsql
security definer
volatile
set search_path = ''
as $$
declare result jsonb;
begin
  perform public.require_platform_admin(false);
  select coalesce(jsonb_agg(jsonb_build_object(
    'user_id', m.user_id,
    'user_number', p.user_number,
    'user_reference', 'U-' || lpad(p.user_number::text, 8, '0'),
    'membership_id', m.id,
    'display_name', coalesce(nullif(trim(p.display_name), ''), split_part(u.email, '@', 1), 'User'),
    'email', u.email, 'role_code', m.role_code, 'membership_active', m.active,
    'platform_status', coalesce(a.status, 'active'), 'platform_reason', a.reason,
    'joined_at', m.created_at
  ) order by m.created_at), '[]'::jsonb) into result
  from public.organization_memberships m
  join auth.users u on u.id = m.user_id
  left join public.profiles p on p.id = m.user_id
  left join public.platform_user_access a on a.user_id = m.user_id
  where m.organization_id = target_org;
  return result;
end;
$$;

create or replace function public.get_platform_admin_console()
returns jsonb
language plpgsql
security definer
volatile
set search_path = ''
as $$
declare result jsonb;
begin
  perform public.require_platform_admin(false);
  select jsonb_build_object(
    'organizations', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', o.id, 'business_number', o.business_number,
        'business_reference', 'S-' || lpad(o.business_number::text, 8, '0'),
        'display_name', o.display_name, 'created_at', o.created_at,
        'member_count', (select count(*) from public.organization_memberships m where m.organization_id = o.id and m.active),
        'plan_code', p.code, 'subscription_status', s.status,
        'period_end', coalesce(s.current_period_end, s.trial_ends_at)
      ) order by o.created_at desc)
      from public.organizations o
      left join public.organization_subscriptions s on s.organization_id = o.id
      left join public.subscription_plans p on p.id = s.plan_id
    ), '[]'::jsonb),
    'plans', coalesce((
      select jsonb_agg(
        to_jsonb(p) || jsonb_build_object('term_prices', coalesce((
          select jsonb_agg(jsonb_build_object('term_months', pp.term_months, 'price_afn', pp.price_afn) order by pp.term_months)
          from public.subscription_plan_prices pp where pp.plan_id = p.id and pp.active
        ), '[]'::jsonb)) order by p.sort_order, p.id
      ) from public.subscription_plans p
    ), '[]'::jsonb),
    'providers', coalesce((select jsonb_agg(to_jsonb(pc) order by pc.code) from public.payment_provider_configs pc), '[]'::jsonb),
    'payment_requests', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', r.id, 'organization_id', r.organization_id, 'organization_name', o.display_name,
        'business_reference', 'S-' || lpad(o.business_number::text, 8, '0'),
        'plan_id', r.plan_id, 'plan_name', p.name_en, 'provider_code', r.provider_code,
        'amount_afn', r.amount_afn, 'term_months', r.term_months,
        'payer_reference', r.payer_reference, 'payer_note', r.payer_note,
        'status', r.status, 'requested_at', r.requested_at
      ) order by r.requested_at desc)
      from public.subscription_payment_requests r
      join public.organizations o on o.id = r.organization_id
      join public.subscription_plans p on p.id = r.plan_id
      where r.status in ('submitted', 'under_review', 'awaiting_payment')
    ), '[]'::jsonb),
    'audit_events', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', recent.id, 'event_type', recent.event_type,
        'target_organization_id', recent.target_organization_id,
        'organization_name', recent.organization_name,
        'target_user_id', recent.target_user_id, 'created_at', recent.created_at
      ) order by recent.created_at desc)
      from (
        select a.id, a.event_type, a.target_organization_id, o.display_name as organization_name,
          a.target_user_id, a.created_at
        from public.platform_audit_events a
        left join public.organizations o on o.id = a.target_organization_id
        order by a.created_at desc limit 100
      ) recent
    ), '[]'::jsonb),
    'counts', jsonb_build_object(
      'organizations', (select count(*) from public.organizations),
      'active_subscriptions', (select count(*) from public.organization_subscriptions where status in ('trial', 'active')),
      'pending_payments', (select count(*) from public.subscription_payment_requests where status in ('submitted', 'under_review')),
      'suspended_users', (select count(*) from public.platform_user_access where status = 'suspended')
    )
  ) into result;
  return result;
end;
$$;

create or replace function public.search_counterparties_v7(target_org uuid, search_text text default null)
returns table (
  id uuid,
  customer_number bigint,
  customer_reference text,
  branch_id uuid,
  display_name text,
  counterparty_type text,
  risk_status text,
  phone text,
  notes text
)
language sql
security definer
stable
set search_path = ''
as $$
  select cp.id, cp.customer_number, 'C-' || lpad(cp.customer_number::text, 8, '0'),
    cp.branch_id, cp.display_name, cp.counterparty_type, cp.risk_status, cp.phone, cp.notes
  from public.counterparties cp
  where cp.organization_id = target_org
    and cp.risk_status <> 'blocked'
    and (
      public.can_access_branch_v6(target_org, cp.branch_id, 'customers.manage')
      or public.can_access_branch_v6(target_org, cp.branch_id, 'transactions.view')
      or public.can_access_branch_v6(target_org, cp.branch_id, 'compliance.review')
    )
    and (
      nullif(trim(search_text), '') is null
      or cp.display_name ilike '%' || trim(search_text) || '%'
      or coalesce(cp.phone, '') ilike '%' || trim(search_text) || '%'
      or cp.customer_number::text = regexp_replace(trim(search_text), '[^0-9]', '', 'g')
      or ('C-' || lpad(cp.customer_number::text, 8, '0')) ilike '%' || trim(search_text) || '%'
    )
  order by cp.display_name, cp.id;
$$;

create or replace function public.search_transaction_history_v7(
  target_org uuid,
  search_text text default null,
  target_from date default null,
  target_to date default null,
  page_size integer default 100
)
returns jsonb
language sql
security definer
stable
set search_path = ''
as $$
  with unique_entries as materialized (
    select distinct on (sl.journal_entry_id)
      sl.journal_entry_id, sl.branch_id, sl.entry_status, sl.occurred_at,
      sl.created_by, sl.financial_event_id, sl.immutable_reference,
      sl.event_type, sl.event_metadata
    from public.get_scoped_report_ledger_lines_v6(target_org, target_from, target_to, null, null, 'transactions.view') sl
    order by sl.journal_entry_id, sl.account_id
  ), result_rows as (
    select ue.occurred_at, ue.journal_entry_id, jsonb_build_object(
      'id', ue.journal_entry_id,
      'transaction_number', je.transaction_number,
      'transaction_reference', 'T-' || lpad(je.transaction_number::text, 8, '0'),
      'status', ue.entry_status, 'memo', je.memo, 'occurred_at', ue.occurred_at,
      'branch_id', ue.branch_id, 'event_type', ue.event_type,
      'immutable_reference', ue.immutable_reference,
      'receipt_number', r.receipt_number,
      'source_account_name', ue.event_metadata->>'source_account_name',
      'destination_account_name', ue.event_metadata->>'destination_account_name',
      'source_account_kind', ue.event_metadata->>'source_account_kind',
      'destination_account_kind', ue.event_metadata->>'destination_account_kind',
      'cashbox_name', cb.name, 'counterparty_name', cp.display_name,
      'customer_number', cp.customer_number,
      'customer_reference', case when cp.customer_number is null then null else 'C-' || lpad(cp.customer_number::text, 8, '0') end,
      'employee_name', coalesce(nullif(trim(pr.display_name), ''), 'Team member'),
      'given_amount', ue.event_metadata->>'sold_amount', 'given_currency', ue.event_metadata->>'sold_currency',
      'received_amount', ue.event_metadata->>'bought_amount', 'received_currency', ue.event_metadata->>'bought_currency',
      'currency_code', coalesce(ue.event_metadata->>'currency', ue.event_metadata->>'sold_currency'),
      'amount', coalesce(ue.event_metadata->>'amount', ue.event_metadata->>'sold_amount'),
      'customer_rate', ue.event_metadata->>'customer_rate',
      'fee_amount', ue.event_metadata->>'fee_amount', 'fee_currency', ue.event_metadata->>'fee_currency'
    ) row_data
    from unique_entries ue
    join public.journal_entries je on je.id = ue.journal_entry_id
    left join public.cashboxes cb on cb.id = case
      when ue.event_metadata->>'cashbox_id' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        then (ue.event_metadata->>'cashbox_id')::uuid else null end
    left join public.financial_events fe on fe.id = ue.financial_event_id
    left join public.counterparties cp on cp.id = coalesce(fe.counterparty_id, case
      when ue.event_metadata->>'counterparty_id' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        then (ue.event_metadata->>'counterparty_id')::uuid else null end) and cp.organization_id = target_org
    left join public.profiles pr on pr.id = ue.created_by
    left join public.receipts r on r.journal_entry_id = ue.journal_entry_id and r.organization_id = target_org
    where nullif(trim(search_text), '') is null
      or je.transaction_number::text = regexp_replace(trim(search_text), '[^0-9]', '', 'g')
      or ('T-' || lpad(je.transaction_number::text, 8, '0')) ilike '%' || trim(search_text) || '%'
      or coalesce(r.receipt_number, '') ilike '%' || trim(search_text) || '%'
      or coalesce(ue.immutable_reference, '') ilike '%' || trim(search_text) || '%'
      or coalesce(cp.display_name, '') ilike '%' || trim(search_text) || '%'
      or coalesce(cp.phone, '') ilike '%' || trim(search_text) || '%'
      or cp.customer_number::text = regexp_replace(trim(search_text), '[^0-9]', '', 'g')
    order by ue.occurred_at desc, ue.journal_entry_id desc
    limit least(greatest(page_size, 1), 1000)
  )
  select coalesce(jsonb_agg(result_rows.row_data order by result_rows.occurred_at desc, result_rows.journal_entry_id desc), '[]'::jsonb)
  from result_rows;
$$;

create or replace function public.get_transaction_detail(target_org uuid, target_entry uuid)
returns jsonb
language plpgsql
security definer
stable
set search_path = ''
as $$
declare result jsonb;
declare branch_id_value uuid;
declare cashbox_id_value uuid;
begin
  select je.branch_id, case
    when fe.metadata->>'cashbox_id' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
      then (fe.metadata->>'cashbox_id')::uuid else null end
  into branch_id_value, cashbox_id_value
  from public.journal_entries je join public.financial_events fe on fe.id = je.financial_event_id
  where je.id = target_entry and je.organization_id = target_org;
  if not found then return null; end if;
  perform public.require_capability(target_org, 'transactions.view', jsonb_strip_nulls(jsonb_build_object(
    'branch_id', branch_id_value, 'cashbox_id', cashbox_id_value
  )));
  select jsonb_build_object(
    'id', je.id, 'transaction_number', je.transaction_number,
    'transaction_reference', 'T-' || lpad(je.transaction_number::text, 8, '0'),
    'status', je.status, 'memo', je.memo, 'occurred_at', je.occurred_at,
    'branch_id', je.branch_id, 'event_type', fe.event_type,
    'immutable_reference', fe.immutable_reference, 'receipt_number', r.receipt_number,
    'source_account_name', fe.metadata->>'source_account_name',
    'destination_account_name', fe.metadata->>'destination_account_name',
    'source_account_kind', fe.metadata->>'source_account_kind',
    'destination_account_kind', fe.metadata->>'destination_account_kind',
    'cashbox_name', cb.name, 'counterparty_name', cp.display_name,
    'customer_number', cp.customer_number,
    'customer_reference', case when cp.customer_number is null then null else 'C-' || lpad(cp.customer_number::text, 8, '0') end,
    'employee_name', coalesce(nullif(trim(pr.display_name), ''), 'Team member'),
    'given_amount', fe.metadata->>'sold_amount', 'given_currency', fe.metadata->>'sold_currency',
    'received_amount', fe.metadata->>'bought_amount', 'received_currency', fe.metadata->>'bought_currency',
    'currency_code', coalesce(fe.metadata->>'currency', fe.metadata->>'sold_currency'),
    'amount', coalesce(fe.metadata->>'amount', fe.metadata->>'sold_amount'),
    'customer_rate', fe.metadata->>'customer_rate',
    'fee_amount', fe.metadata->>'fee_amount', 'fee_currency', fe.metadata->>'fee_currency'
  ) into result
  from public.journal_entries je
  join public.financial_events fe on fe.id = je.financial_event_id
  left join public.cashboxes cb on cb.id = cashbox_id_value and cb.organization_id = target_org
  left join public.counterparties cp on cp.id = fe.counterparty_id and cp.organization_id = target_org
  left join public.profiles pr on pr.id = je.created_by
  left join public.receipts r on r.journal_entry_id = je.id and r.organization_id = target_org
  where je.id = target_entry and je.organization_id = target_org;
  return result;
end;
$$;

revoke all on function public.get_billing_portal(uuid) from public, anon;
revoke all on function public.create_subscription_payment_request(uuid, uuid, text, smallint, text, text) from public, anon;
revoke all on function public.decide_subscription_payment(uuid, text, text) from public, anon;
revoke all on function public.get_platform_organization_users(uuid) from public, anon;
revoke all on function public.get_platform_admin_console() from public, anon;
revoke all on function public.search_counterparties_v7(uuid, text) from public, anon;
revoke all on function public.search_transaction_history_v7(uuid, text, date, date, integer) from public, anon;
revoke all on function public.get_transaction_detail(uuid, uuid) from public, anon;

grant execute on function public.get_billing_portal(uuid) to authenticated;
grant execute on function public.create_subscription_payment_request(uuid, uuid, text, smallint, text, text) to authenticated;
grant execute on function public.decide_subscription_payment(uuid, text, text) to authenticated;
grant execute on function public.get_platform_organization_users(uuid) to authenticated;
grant execute on function public.get_platform_admin_console() to authenticated;
grant execute on function public.search_counterparties_v7(uuid, text) to authenticated;
grant execute on function public.search_transaction_history_v7(uuid, text, date, date, integer) to authenticated;
grant execute on function public.get_transaction_detail(uuid, uuid) to authenticated;
